name: quizgyan
description: "A new Flutter project."

publish_to: 'none'  
version: 1.0.1+2
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.6
  store_redirect: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

   
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/logo.png  
  android_12:
    image: assets/icons/logo.png  
    color: "#FFFFFF"
