class Question {
  final String questionText;
  final List<String> options;
  final int answerIndex;
  final int id;
  final String category;

  Question({
    required this.questionText,
    required this.options,
    required this.answerIndex,
    required this.id,
    required this.category,
  });
}

List<Question> cultureQuestions = [
  // Nepali Culture - Easy Questions - 2 Options
  Question(id: 101, category: "Nepali Culture", questionText: "दशैंमा निधारमा लगाइने रातो टीका केको प्रतीक हो? (What does the red tika applied on the forehead during Dashain symbolize?)", options: ["खुशी (Happiness)", "समृद्धि र विजय (Prosperity and victory)"], answerIndex: 1),
  Question(id: 102, category: "Nepali Culture", questionText: "नेपालको राष्ट्रिय पोशाक पुरुषका लागि के हो? (What is the national dress for men in Nepal?)", options: ["पगडी (Turban)", "दौरा सुरुवाल (Daura Suruwal)"], answerIndex: 1),
  Question(id: 103, category: "Nepali Culture", questionText: "बुद्धको जन्मस्थल नेपालको कुन ठाउँमा छ? (In which place in Nepal is the birthplace of Buddha?)", options: ["पोखरा (Pokhara)", "लुम्बिनी (Lumbini)"], answerIndex: 1),
  Question(id: 104, category: "Nepali Culture", questionText: "नेपालमा नयाँ वर्ष कुन चाडबाट सुरु हुन्छ? (Which festival marks the New Year in Nepal?)", options: ["तिहार (Tihar)", "बिक्रम संवत् (Bikram Sambat)"], answerIndex: 1),
  Question(id: 105, category: "Nepali Culture", questionText: "नेपालको राष्ट्रिय फूल कुन हो? (What is the national flower of Nepal?)", options: ["गुलाब (Rose)", "लालीगुराँस (Rhododendron)"], answerIndex: 1),
  Question(id: 106, category: "Nepali Culture", questionText: "मृतकको आत्माको शान्तिका लागि मनाइने नेवारी चाड कुन हो? (Which Newari festival is celebrated for the peace of the deceased's soul?)", options: ["इन्द्रजात्रा (Indra Jatra)", "गाईजात्रा (Gai Jatra)"], answerIndex: 1),
  Question(id: 107, category: "Nepali Culture", questionText: "विवाहमा बेहुलीले बेहुलाको घर जाँदा कुन परम्परागत बाजा बजाइन्छ? (Which traditional instrument is played when the bride goes to the groom's house during a wedding?)", options: ["बाँसुरी (Flute)", "पञ्चे बाजा (Panche Baja)"], answerIndex: 1),
  Question(id: 108, category: "Nepali Culture", questionText: "कुन नेपाली खाना मकैको पिठोबाट बनाइन्छ र दालसँग खाइन्छ? (Which Nepali food is made from cornflour and eaten with lentil soup?)", options: ["चाउचाउ (Noodles)", "ढिँडो (Dhindo)"], answerIndex: 1),
  Question(id: 109, category: "Nepali Culture", questionText: "नेपालको राष्ट्रिय जनावर कुन हो? (What is the national animal of Nepal?)", options: ["बाघ (Tiger)", "गाई (Cow)"], answerIndex: 1),
  Question(id: 110, category: "Nepali Culture", questionText: "नेपालमा 'भैलो' र 'देउसी' कुन चाडमा खेलिन्छ? (In which festival are 'Bhailo' and 'Deusi' played in Nepal?)", options: ["दशैं (Dashain)", "तिहार (Tihar)"], answerIndex: 1),

  // World Culture - Easy Questions - 2 Options
  Question(id: 111, category: "World Culture", questionText: "पिज्जा (Pizza) कुन देशको परम्परागत खाना हो? (Which country's traditional food is Pizza?)", options: ["चीन (China)", "इटाली (Italy)"], answerIndex: 1),
  Question(id: 112, category: "World Culture", questionText: "क्रिसमस (Christmas) कुन धर्मको प्रमुख चाड हो? (Which religion's major festival is Christmas?)", options: ["हिन्दु धर्म (Hinduism)", "ईसाई धर्म (Christianity)"], answerIndex: 1),
  Question(id: 113, category: "World Culture", questionText: "एकीकृत प्रतिमा 'स्ट्याचु अफ लिबर्टी' (Statue of Liberty) कुन शहरमा अवस्थित छ? (In which city is the iconic 'Statue of Liberty' located?)", options: ["लन्डन (London)", "न्यु योर्क (New York)"], answerIndex: 1),
  Question(id: 114, category: "World Culture", questionText: "चिनियाँ नयाँ वर्षमा कुन जनावरको नृत्य सामान्यतया प्रदर्शन गरिन्छ? (Which animal's dance is commonly performed during Chinese New Year?)", options: ["बाघ (Tiger)", "ड्रागन (Dragon)"], answerIndex: 1),
  Question(id: 115, category: "World Culture", questionText: "पिरामिडहरू (Pyramids) कुन देशको प्रसिद्ध संरचना हो? (Pyramids are famous structures in which country?)", options: ["भारत (India)", "इजिप्ट (Egypt)"], answerIndex: 1),

  // Nepali Culture - Medium Questions - 3-4 Options
  Question(id: 116, category: "Nepali Culture", questionText: "कुमारी (Living Goddess) परम्परा कुन समुदायमा प्रचलित छ? (In which community is the Kumari (Living Goddess) tradition prevalent?)", options: ["गुरुङ (Gurung)", "नेवार (Newar)", "तामाङ (Tamang)"], answerIndex: 1),
  Question(id: 117, category: "Nepali Culture", questionText: "नेपालको कुन सांस्कृतिक समूहले 'लसोसार' (Lhosar) मनाउँछ? (Which cultural group in Nepal celebrates 'Lhosar'?)", options: ["ब्राह्मण (Brahmin)", "छेत्री (Chhetri)", "गुरुङ, तामाङ, शेर्पा (Gurung, Tamang, Sherpa)"], answerIndex: 2),
  Question(id: 118, category: "Nepali Culture", questionText: "काठमाडौं उपत्यकाको कुन जात्रा रथ यात्राका लागि प्रसिद्ध छ? (Which jatra in Kathmandu Valley is famous for its chariot procession?)", options: ["घोडेजात्रा (Ghode Jatra)", "मच्छिन्द्रनाथको भोटो जात्रा (Machhindranath Bhoto Jatra)", "सिन्दुर जात्रा (Sindoor Jatra)"], answerIndex: 1),
  Question(id: 119, category: "Nepali Culture", questionText: "नेपालमा 'गाईजात्रा' चाड मनाउने मुख्य उद्देश्य के हो? (What is the main purpose of celebrating 'Gai Jatra' festival in Nepal?)", options: ["वर्षाको लागि प्रार्थना (Praying for rain)", "मृतक आफन्तहरूको सम्झना (Commemorating deceased relatives)", "नयाँ फसलको उत्सव (Celebrating new harvest)"], answerIndex: 1),
  Question(id: 120, category: "Nepali Culture", questionText: "नेपालको प्रसिद्ध पशुपतिनाथ मन्दिर कुन नदीको किनारमा अवस्थित छ? (On the banks of which river is Nepal's famous Pashupatinath Temple located?)", options: ["सेती नदी (Seti River)", "बागमती नदी (Bagmati River)", "गण्डकी नदी (Gandaki River)"], answerIndex: 1),
  Question(id: 121, category: "Nepali Culture", questionText: "नेपालमा कुन चाडमा बहिनीले दाजुभाइलाई टीका लगाइदिन्छन्? (In which festival in Nepal do sisters put tika on their brothers?)", options: ["होली (Holi)", "तिहार (Tihar)", "दशैं (Dashain)"], answerIndex: 1),
  Question(id: 122, category: "Nepali Culture", questionText: "नेपालको पहिलो विश्व सम्पदा सूचीमा परेको स्थान कुन हो? (What is Nepal's first UNESCO World Heritage Site?)", options: ["चितवन राष्ट्रिय निकुञ्ज (Chitwan National Park)", "सगरमाथा राष्ट्रिय निकुञ्ज (Sagarmatha National Park)", "काठमाडौं उपत्यका (Kathmandu Valley)"], answerIndex: 2),
  Question(id: 123, category: "Nepali Culture", questionText: "नेपालमा 'जनै पूर्णिमा' को दिन विशेषगरी कुन कार्य गरिन्छ? (What is a special activity performed on 'Janai Purnima' in Nepal?)", options: ["राखी बाँध्ने (Tying Rakhi)", "जनै फेर्ने र रक्षाबन्धन गर्ने (Changing Janai and tying Rakshabandhan)", "दशावतार हेर्ने (Watching Dashavatar)"], answerIndex: 1),
  Question(id: 124, category: "Nepali Culture", questionText: "नेपालको परम्परागत वास्तुकला शैलीमा प्रायः कुन सामग्री प्रयोग गरिन्छ? (Which material is commonly used in traditional Nepali architectural style?)", options: ["सिमेन्ट (Cement)", "ढुङ्गा र काठ (Stone and wood)", "फलाम (Iron)"], answerIndex: 1),
  Question(id: 125, category: "Nepali Culture", questionText: "नेपालको तराई क्षेत्रमा मनाइने प्रमुख चाड कुन हो? (Which is a major festival celebrated in the Terai region of Nepal?)", options: ["साकेला (Sakela)", "छठ पर्व (Chhath Parva)", "उधौली (Udhauli)"], answerIndex: 1),

  // World Culture - Medium Questions - 3-4 Options
  Question(id: 126, category: "World Culture", questionText: "जापानको परम्परागत पोशाकलाई के भनिन्छ? (What is the traditional attire of Japan called?)", options: ["सारी (Sari)", "किमोज (Kimono)", "तुनिक (Tunic)"], answerIndex: 1),
  Question(id: 127, category: "World Culture", questionText: "मुस्लिम समुदायको प्रमुख चाड 'ईद' ले केको प्रतीक हो? (What does the major Muslim festival 'Eid' symbolize?)", options: ["नयाँ वर्ष (New Year)", "बलिदान र एकता (Sacrifice and unity)", "वसन्त ऋतुको आगमन (Arrival of spring)"], answerIndex: 1),
  Question(id: 128, category: "World Culture", questionText: "प्राचीन ग्रीकहरूले कुन क्षेत्रमा प्रमुख सांस्कृतिक योगदान दिएका थिए? (In which area did the ancient Greeks make major cultural contributions?)", options: ["संगीत (Music)", "दर्शनशास्त्र र लोकतन्त्र (Philosophy and democracy)", "प्रविधि (Technology)"], answerIndex: 1),
  Question(id: 129, category: "World Culture", questionText: "भारतमा 'होली' पर्वमा मुख्यतया के गरिन्छ? (What is mainly done during the 'Holi' festival in India?)", options: ["दीप प्रज्वलन (Lighting lamps)", "रंग खेल्ने र मिठाई खाने (Playing with colors and eating sweets)", "उपवास बस्ने (Fasting)"], answerIndex: 1),
  Question(id: 130, category: "World Culture", questionText: "रोमन साम्राज्यको आधिकारिक भाषा के थियो, जसले युरोपेली संस्कृतिमा गहिरो प्रभाव पार्यो? (What was the official language of the Roman Empire, which deeply influenced European culture?)", options: ["ग्रीक (Greek)", "ल्याटिन (Latin)", "अरबी (Arabic)"], answerIndex: 1),

  // Nepali Culture - Hard Questions - 4-5 Options
  Question(id: 131, category: "Nepali Culture", questionText: "नेपालमा 'छठ पर्व' को मुख्य अनुष्ठान कुन नदीसँग सम्बन्धित छ? (Which river is primarily associated with the main rituals of 'Chhath Parva' in Nepal?)", options: ["कोसी नदी (Koshi River)", "गण्डकी नदी (Gandaki River)", "बागमती नदी (Bagmati River)", "सूर्य देवताको पूजा (Worship of Sun God)", "कन्काई नदी (Kankai River)"], answerIndex: 3), // Chhath is about Sun God, not specific river
  Question(id: 132, category: "Nepali Culture", questionText: "नेपालको कुन जाति समूहको 'मुन्दुम' भन्ने मौलिक धर्म र संस्कृति छ? (Which ethnic group in Nepal has an indigenous religion and culture called 'Mundhum'?)", options: ["गुरुङ (Gurung)", "मगर (Magar)", "राई र लिम्बु (Rai and Limbu)", "तामाङ (Tamang)", "शेर्पा (Sherpa)"], answerIndex: 2),
  Question(id: 133, category: "Nepali Culture", questionText: "नेपालको 'महाभारत' क्षेत्रमा प्रचलित मुख्य सांस्कृतिक अभ्यास कुन हो? (What is a primary cultural practice prevalent in the 'Mahabharat' region of Nepal?)", options: ["गुम्बा भ्रमण (Visiting monasteries)", "कृषिमा आधारित जीवनशैली र लोकगीत (Agriculture-based lifestyle and folk songs)", "समुद्री व्यापार (Sea trade)", "औद्योगिक विकास (Industrial development)", "हिमाल आरोहण (Mountain climbing)"], answerIndex: 1),
  Question(id: 134, category: "Nepali Culture", questionText: "नेपालमा 'भोटेकोशी' नदीको नाम कुन सांस्कृतिक प्रभावबाट आएको हो? (From which cultural influence does the 'Bhote Koshi' river in Nepal get its name?)", options: ["भारतीय संस्कृति (Indian culture)", "तिब्बती/भोट संस्कृति (Tibetan/Bhot culture)", "स्थानीय नेवारी संस्कृति (Local Newari culture)", "मगर संस्कृति (Magar culture)", "थाकाली संस्कृति (Thakali culture)"], answerIndex: 1),
  Question(id: 135, category: "Nepali Culture", questionText: "नेपालको कुन चाडमा मानिसहरूले एकअर्कालाई 'शुभकामना' को रूपमा 'सगुन' दिन्छन्? (In which Nepali festival do people give 'Sagan' as a 'good wish' to each other?)", options: ["होली (Holi)", "दशैं (Dashain)", "जन्मदिन (Birthday)", "विवाह (Wedding)", "चाँदनी (Chadni)"], answerIndex: 3), // Sagan is primarily a Newari tradition for various auspicious occasions like weddings, birthdays, etc.
  Question(id: 136, category: "Nepali Culture", questionText: "काठमाडौं उपत्यका बाहिरको कुन शहर 'कला र वास्तुकला' को लागि प्रसिद्ध छ र यसमा थुप्रै प्राचीन मन्दिरहरू छन्? (Which city outside Kathmandu Valley is famous for 'art and architecture' and has many ancient temples?)", options: ["पोखरा (Pokhara)", "धरान (Dharan)", "जनकपुर (Janakpur)", "गोरखा (Gorkha)", "बुटवल (Butwal)"], answerIndex: 2),
  Question(id: 137, category: "Nepali Culture", questionText: "नेपालको कुन सांस्कृतिक परम्परामा 'गुन्यू चोली' को विशेष महत्व छ? (In which Nepali cultural tradition does 'Gunya Choli' hold special significance?)", options: ["विवाह समारोह (Wedding ceremony)", "उपनयन संस्कार (Upanayan ceremony)", "चेलीबेटी सम्मान (Respect for daughters/sisters)", "मन्जुश्रीको पूजा (Worship of Manjushree)", "चाडपर्व (Festivals)"], answerIndex: 0),
  Question(id: 138, category: "Nepali Culture", questionText: "नेपालमा 'श्रीपञ्चमी' को दिन विशेष गरी कुन देवीको पूजा गरिन्छ? (Which goddess is primarily worshipped on the day of 'Shree Panchami' in Nepal?)", options: ["लक्ष्मी (Lakshmi)", "दुर्गा (Durga)", "सरस्वती (Saraswati)", "काली (Kali)", "सीता (Sita)"], answerIndex: 2),
  Question(id: 139, category: "Nepali Culture", questionText: "नेपालको कुन पर्वमा प्रकृति र पृथ्वीको पूजा गरिन्छ र यसलाई 'धरती पूजा' पनि भनिन्छ? (Which festival in Nepal involves worshipping nature and the Earth, also known as 'Dharti Puja'?)", options: ["तीज (Teej)", "माघे संक्रान्ति (Maghe Sankranti)", "उधौली/उभौली (Udhauli/Ubhauli)", "फागु पूर्णिमा (Fagu Purnima)", "बडादशैं (Bada Dashain)"], answerIndex: 2), // Udhauli/Ubhauli by Kiratis are closely tied to nature.
  Question(id: 140, category: "Nepali Culture", questionText: "नेपालको 'तराई' क्षेत्रमा प्रचलित 'झिझिया' नृत्य कुन अवसरमा गरिन्छ? (On which occasion is the 'Jhijiya' dance, popular in the 'Terai' region of Nepal, performed?)", options: ["विवाह (Wedding)", "नवरात्रिको समयमा (During Navaratri)", "जन्मदिन (Birthday)", "नयाँ वर्ष (New Year)", "बाली भित्र्याउने बेला (Harvest time)"], answerIndex: 1),
  Question(id: 141, category: "Nepali Culture", questionText: "नेपालको कुन सांस्कृतिक परम्परा 'सती' प्रथासँग सम्बन्धित थियो, जुन अहिले समाप्त भइसकेको छ? (Which Nepali cultural tradition was related to the 'Sati' practice, which has now been abolished?)", options: ["दहेज प्रथा (Dowry system)", "बाल विवाह (Child marriage)", "विधवा दहन (Widow immolation)", "बहुविवाह (Polygamy)", "छुवाछूत (Untouchability)"], answerIndex: 2),
  Question(id: 142, category: "Nepali Culture", questionText: "नेपालको कुन चाडमा 'आगो' लाई पवित्र मानिन्छ र 'दिप प्रज्वलन' गरिन्छ? (In which Nepali festival is 'fire' considered sacred and 'lamp lighting' performed?)", options: ["होली (Holi)", "दशैं (Dashain)", "तिहार (Tihar)", "माघे संक्रान्ति (Maghe Sankranti)", "शिवरात्री (Shivaratri)"], answerIndex: 2),
  Question(id: 143, category: "Nepali Culture", questionText: "काठमाडौं उपत्यकाको 'पाटन दरबार स्क्वायर' कुन वंशका राजाहरूको कला र वास्तुकलाको उत्कृष्ट उदाहरण हो? (Patan Durbar Square in Kathmandu Valley is an excellent example of the art and architecture of which dynasty's kings?)", options: ["मल्ल वंश (Malla Dynasty)", "शाह वंश (Shah Dynasty)", "लिच्छवी वंश (Licchavi Dynasty)", "किरात वंश (Kirat Dynasty)", "गोपाल वंश (Gopal Dynasty)"], answerIndex: 0),
  Question(id: 144, category: "Nepali Culture", questionText: "नेपालमा 'भैलो' र 'देउसी' खेल खेल्दा कुन उपकरणहरू प्रयोग गरिन्छ? (Which instruments are used when playing 'Bhailo' and 'Deusi' in Nepal?)", options: ["गिटार र ड्रम (Guitar and drum)", "मादल र खैंजडी (Madal and Khainjadi)", "पियानो र भायोलिन (Piano and violin)", "ढोलक र तबला (Dholak and Tabla)", "सिन्का र ढुङ्गा (Sticks and stones)"], answerIndex: 1),
  Question(id: 145, category: "Nepali Culture", questionText: "नेपालको कुन चाडमा 'पशुबलि' दिने परम्परा छ, जुन अहिले कम हुँदै गइरहेको छ? (In which Nepali festival is there a tradition of 'animal sacrifice', which is now decreasing?)", options: ["बुद्ध जयन्ती (Buddha Jayanti)", "दशैं (Dashain)", "माघे संक्रान्ति (Maghe Sankranti)", "जन्माष्टमी (Janmashtami)", "छठ पर्व (Chhath Parva)"], answerIndex: 1),

  // World Culture - Hard Questions - 4-5 Options
  Question(id: 146, category: "World Culture", questionText: "प्राचीन इजिप्टको 'हाइरोग्लिफिक्स' (hieroglyphics) के हो? (What are 'hieroglyphics' in ancient Egypt?)", options: ["मौखिक कथाहरू (Oral stories)", "पूजाको विधि (Method of worship)", "चित्र-आधारित लेखन प्रणाली (Picture-based writing system)", "मन्दिरको नाम (Name of a temple)", "मृतकको चिहान (Tomb of the dead)"], answerIndex: 2),
  Question(id: 147, category: "World Culture", questionText: "दक्षिण अमेरिकी 'इन्का' (Inca) सभ्यता कुन क्षेत्रमा केन्द्रित थियो? (In which region was the South American 'Inca' civilization centered?)", options: ["मेसोअमेरिका (Mesoamerica)", "एन्डिज पर्वतमाला (Andes Mountains)", "अमेजन वर्षावन (Amazon Rainforest)", "क्यारिबियन द्वीपसमूह (Caribbean Islands)", "सहारा मरुभूमि (Sahara Desert)"], answerIndex: 1),
  Question(id: 148, category: "World Culture", questionText: "जर्मनीमा 'अक्टोबरफेस्ट' (Oktoberfest) मुख्यतया केको लागि मनाइन्छ? (What is 'Oktoberfest' primarily celebrated for in Germany?)", options: ["वसन्तको स्वागत (Welcoming spring)", "बियर र लोक परम्परा (Beer and folk traditions)", "नयाँ वर्षको उत्सव (New Year celebration)", "किसानहरूको सम्मान (Honoring farmers)", "राष्ट्रिय स्वतन्त्रता दिवस (National Independence Day)"], answerIndex: 1),
  Question(id: 149, category: "World Culture", questionText: "अफ्रीकी संस्कृतिमा 'ग्रिओट' (Griot) को भूमिका के हो? (What is the role of a 'Griot' in African culture?)", options: ["योद्धा (Warrior)", "किसान (Farmer)", "कथाकार, संगीतकार र इतिहासकार (Storyteller, musician, and historian)", "व्यापारी (Trader)", "डाक्टर (Doctor)"], answerIndex: 2),
  Question(id: 150, category: "World Culture", questionText: "चीनको 'महान पर्खाल' (Great Wall of China) बनाउनुको मुख्य उद्देश्य के थियो? (What was the primary purpose of building the 'Great Wall of China'?)", options: ["व्यापार मार्गको लागि (For trade routes)", "मनोरञ्जनको लागि (For entertainment)", "उत्तरी आक्रमणकारीहरूबाट रक्षा गर्न (To defend against northern invaders)", "पर्यटन बढाउन (To promote tourism)", "जलवायु परिवर्तन नियन्त्रण गर्न (To control climate change)"], answerIndex: 2),
  Question(id: 151, category: "World Culture", questionText: "जापानको 'चिया समारोह' (Tea Ceremony) को मुख्य दर्शन के हो? (What is the main philosophy of Japan's 'Tea Ceremony'?)", options: ["छिटो चिया पिउने (Drinking tea quickly)", "सामाजिक जमघट (Social gathering)", "सामञ्जस्य, सम्मान, शुद्धता र शान्ति (Harmony, respect, purity, and tranquility)", "आर्थिक लेनदेन (Economic transaction)", "राजनीतिक छलफल (Political discussion)"], answerIndex: 2),
  Question(id: 152, category: "World Culture", questionText: "प्राचीन रोममा 'कोलोसियम' (Colosseum) केको लागि प्रयोग गरिन्थ्यो? (What was the 'Colosseum' used for in ancient Rome?)", options: ["व्यापार बजार (Trade market)", "जनसभा र ग्लेडिएटर खेलहरू (Public assemblies and gladiatorial games)", "धार्मिक समारोह (Religious ceremonies)", "अस्पताल (Hospital)", "विद्यालय (School)"], answerIndex: 1),
  Question(id: 153, category: "World Culture", questionText: "भारतको 'दीपावली' (Diwali) पर्वले केको प्रतीक हो? (What does India's 'Diwali' festival symbolize?)", options: ["अन्धकारमाथि प्रकाशको विजय (Victory of light over darkness)", "वसन्त ऋतुको आगमन (Arrival of spring)", "नयाँ वर्षको सुरुवात (Beginning of a new year)", "प्रेमको उत्सव (Celebration of love)", "बाली भित्र्याउने (Harvesting crops)"], answerIndex: 0),
  Question(id: 154, category: "World Culture", questionText: "ब्राजिलको 'कार्निभल' (Carnival) को मुख्य विशेषता के हो? (What is a main characteristic of Brazil's 'Carnival'?)", options: ["शान्त प्रार्थना (Quiet prayers)", "विशाल परेड, संगीत र नृत्य (Huge parades, music, and dance)", "अध्ययन र अनुसन्धान (Study and research)", "कृषि प्रदर्शन (Agricultural exhibition)", "राजनीतिक बहस (Political debate)"], answerIndex: 1),
  Question(id: 155, category: "World Culture", questionText: "अष्ट्रेलियाका आदिवासीहरूको 'ड्रीमटाइम' (Dreamtime) अवधारणाले के बुझाउँछ? (What does the 'Dreamtime' concept of Australia's Aboriginal people refer to?)", options: ["निद्राको समय (Time for sleep)", "स्वप्नको व्याख्या (Interpretation of dreams)", "सृष्टिको प्राचीन कथा र आध्यात्मिक संसार (Ancient creation stories and spiritual world)", "भविष्यको भविष्यवाणी (Prediction of the future)", "वैज्ञानिक सिद्धान्त (Scientific theories)"], answerIndex: 2),
];
