class Question {
  final int id;
  final String question;
  final List<String> options;
  final String answer;
  final int level;
  final String category;

  Question({
    required this.id,
    required this.question,
    required this.options,
    required this.answer,
    required this.level,
    required this.category,
  });
}

List<Question> nepaliQuizQuestions = [
  // --- Nepal History ---
  Question(
    id: 101,
    question: "नेपालको एकीकरण कसले सुरु गरेका थिए?",
    options: [
      "पृथ्वीनारायण शाह",
      "अंशुवर्मा",
      "जंगबहादुर राणा",
      "भक्तपुरका राजा",
    ],
    answer: "पृथ्वीनारायण शाह",
    level: 1,
    category: "nepal history",
  ),
  Question(
    id: 102,
    question: "गोर्खा राज्यको स्थापना कहिले भयो?",
    options: ["१५५९", "१६१६", "१७२३", "१८०१"],
    answer: "१५५९",
    level: 2,
    category: "nepal history",
  ),
  Question(
    id: 103,
    question: "नेपालमा राणा शासनको सुरुवात कसले गरेका थिए?",
    options: [
      "पृथ्वीनारायण शाह",
      "जंगबहादुर राणा",
      "भीमसेन थापा",
      "अमरसिंह थापा",
    ],
    answer: "जंगबहादुर राणा",
    level: 3,
    category: "nepal history",
  ),
  Question(
    id: 104,
    question: "सिंहदरबारमा आगलागी कहिले भएको थियो?",
    options: ["वि.सं. १९९०", "वि.सं. २००५", "वि.सं. २०२९", "वि.सं. २०४६"],
    answer: "वि.सं. २०२९",
    level: 4,
    category: "nepal history",
  ),
  Question(
    id: 105,
    question: "दरबार हत्याकाण्ड कहिले भएको थियो?",
    options: ["वि.सं. २०५०", "वि.सं. २०५८", "वि.सं. २०६०", "वि.सं. २०६२"],
    answer: "वि.सं. २०५८",
    level: 5,
    category: "nepal history",
  ),
  Question(
    id: 106,
    question:
        "मल्लकालमा सामाजिक सुधारका लागि 'जयस्थिति मल्ल' ले कुन प्रणाली ल्याएका थिए?",
    options: [
      "वर्ण व्यवस्था",
      "मनुस्मृति",
      "कर्मकाण्ड",
      "माथिका कुनै पनि होइन",
    ],
    answer: "वर्ण व्यवस्था",
    level: 6,
    category: "nepal history",
  ),
  Question(
    id: 107,
    question: "लिच्छवि कालमा न्याय हेर्ने अड्डालाई के भनिन्थ्यो?",
    options: ["कोट", "चौतार", "पञ्चायत", "धर्माधिकरण"],
    answer: "धर्माधिकरण",
    level: 2,
    category: "nepal history",
  ),
  Question(
    id: 108,
    question: "नेपालको पहिलो महिला प्रधानन्यायाधीश को हुन्?",
    options: [
      "सुशीला कार्की",
      "विद्यादेवी भण्डारी",
      "ओनसरी घर्ती",
      "शशीकला दाहाल",
    ],
    answer: "सुशीला कार्की",
    level: 3,
    category: "nepal history",
  ),
  Question(
    id: 109,
    question: "किरातकालमा प्रशासन प्रमुखलाई के भनिन्थ्यो?",
    options: ["सामन्त", "माझगाउँले", "करदाता", "सुमङ्गला"],
    answer: "सुमङ्गला",
    level: 4,
    category: "nepal history",
  ),
  Question(
    id: 110,
    question: "पृथ्वीनारायण शाहको जन्म कहिले भएको थियो?",
    options: ["वि.सं. १७७९", "वि.सं. १७८०", "वि.सं. १७८१", "वि.सं. १७८२"],
    answer: "वि.सं. १७७९",
    level: 1,
    category: "nepal history",
  ),
  Question(
    id: 111,
    question: "१०४ वर्ष राणा शासनको अन्त्य कहिले भयो?",
    options: ["वि.सं. २००७", "वि.सं. २०१५", "वि.सं. २०४६", "वि.सं. २०६२"],
    answer: "वि.सं. २००७",
    level: 1,
    category: "nepal history",
  ),
  Question(
    id: 112,
    question: "नेपालको इतिहासमा 'कालो रात' भन्नाले कुन घटनालाई बुझिन्छ?",
    options: [
      "कोत पर्व",
      "भण्डारखाल पर्व",
      "५८ सालको घटना",
      "दरबार हत्याकाण्ड",
    ],
    answer: "कोत पर्व",
    level: 5,
    category: "nepal history",
  ),
  Question(
    id: 113,
    question: "पहिलो शहीद को हुन्?",
    options: ["दशरथ चन्द", "शुक्रराज शास्त्री", "गंगालाल श्रेष्ठ", "लखन थापा"],
    answer: "लखन थापा",
    level: 2,
    category: "nepal history",
  ),
  Question(
    id: 114,
    question: "नेपालको वर्तमान संविधान कहिले जारी भयो?",
    options: ["वि.सं. २०७०", "वि.सं. २०७२", "वि.सं. २०७५", "वि.सं. २०६३"],
    answer: "वि.सं. २०७२",
    level: 1,
    category: "nepal history",
  ),
  Question(
    id: 115,
    question: "नेपालमा दासप्रथाको अन्त्य कहिले भयो?",
    options: ["वि.सं. १९८०", "वि.सं. १९८१", "वि.सं. १९८२", "वि.सं. १९८३"],
    answer: "वि.सं. १९८१",
    level: 3,
    category: "nepal history",
  ),
  Question(
    id: 116,
    question: "नेपालमा लोकतन्त्र दिवस कहिले मनाइन्छ?",
    options: ["वैशाख ११", "फागुन ७", "जेठ १५", "असार १५"],
    answer: "वैशाख ११",
    level: 1,
    category: "nepal history",
  ),
  Question(
    id: 117,
    question: "गोर्खा सैनिकको संगठन कसले गरेका थिए?",
    options: [
      "पृथ्वीनारायण शाह",
      "भीमसेन थापा",
      "जंगबहादुर राणा",
      "अमरसिंह थापा",
    ],
    answer: "पृथ्वीनारायण शाह",
    level: 2,
    category: "nepal history",
  ),
  Question(
    id: 118,
    question: "नेपालको राष्ट्रिय गानका रचयिता को हुन्?",
    options: [
      "माधवप्रसाद घिमिरे",
      "प्रदीपकुमार राई",
      "व्याकुल माइला",
      "धर्मराज थापा",
    ],
    answer: "व्याकुल माइला",
    level: 1,
    category: "nepal history",
  ),
  Question(
    id: 119,
    question: "पाटनका अन्तिम मल्ल राजा को हुन्?",
    options: [
      "सिद्धिनरसिंह मल्ल",
      "योगनरसिंह मल्ल",
      "तेजनरसिंह मल्ल",
      "रणजित मल्ल",
    ],
    answer: "तेजनरसिंह मल्ल",
    level: 4,
    category: "nepal history",
  ),
  Question(
    id: 120,
    question: "नेपालमा 'सती प्रथा' को अन्त्य कसले गरेका थिए?",
    options: ["देवशमशेर", "चन्द्रशमशेर", "जुद्धशमशेर", "पद्मशमशेर"],
    answer: "चन्द्रशमशेर",
    level: 3,
    category: "nepal history",
  ),

  // --- World History ---
  Question(
    id: 201,
    question: "दोस्रो विश्वयुद्ध कहिले सुरु भयो?",
    options: ["१९१४", "१९३९", "१९४५", "१९५०"],
    answer: "१९३९",
    level: 1,
    category: "world history",
  ),
  Question(
    id: 202,
    question: "महान् चिनियाँ पर्खालको निर्माण कसले सुरु गरेका थिए?",
    options: ["कन्फुसियस", "किन शी हुआंग", "माओत्से तुंग", "चंगेज खान"],
    answer: "किन शी हुआंग",
    level: 2,
    category: "world history",
  ),
  Question(
    id: 203,
    question: "फ्रान्सेली क्रान्ति कहिले भएको थियो?",
    options: ["१७७६", "१७८९", "१८०४", "१८१५"],
    answer: "१७८९",
    level: 3,
    category: "world history",
  ),
  Question(
    id: 204,
    question: "क्लियोपेट्रा कुन देशकी रानी थिइन्?",
    options: ["ग्रीस", "रोम", "इजिप्ट", "फारस"],
    answer: "इजिप्ट",
    level: 4,
    category: "world history",
  ),
  Question(
    id: 205,
    question: "रुसी क्रान्तिका नेता को थिए?",
    options: [
      "जोसेफ स्टालिन",
      "भ्लादिमिर लेनिन",
      "निकोलस द्वितीय",
      "लियोन ट्रोट्स्की",
    ],
    answer: "भ्लादिमिर लेनिन",
    level: 5,
    category: "world history",
  ),
  Question(
    id: 206,
    question: "मोहम्मदको जन्म कहिले भएको थियो?",
    options: ["५७० ई.पू.", "६१० ई.पू.", "५७० ई.सं.", "६१० ई.सं."],
    answer: "५७० ई.सं.",
    level: 6,
    category: "world history",
  ),
  Question(
    id: 207,
    question: "अमेरिकाले कहिले स्वतन्त्रता प्राप्त गर्यो?",
    options: ["१७७६", "१७८९", "१८१२", "१८६५"],
    answer: "१७७६",
    level: 1,
    category: "world history",
  ),
  Question(
    id: 208,
    question: "नेपोलियन बोनापार्ट कुन देशका शासक थिए?",
    options: ["इटाली", "जर्मनी", "फ्रान्स", "स्पेन"],
    answer: "फ्रान्स",
    level: 2,
    category: "world history",
  ),
  Question(
    id: 209,
    question: "प्रथम विश्वयुद्ध कहिले अन्त्य भयो?",
    options: ["१९१७", "१९१८", "१९१९", "१९२०"],
    answer: "१९१८",
    level: 2,
    category: "world history",
  ),
  Question(
    id: 210,
    question: "चन्द्रमामा पहिलो पटक पाइला टेक्ने व्यक्ति को हुन्?",
    options: ["युरी गागारिन", "नील आर्मस्ट्रङ", "बज एल्ड्रिन", "माइकल कोलिन्स"],
    answer: "नील आर्मस्ट्रङ",
    level: 1,
    category: "world history",
  ),
  Question(
    id: 211,
    question: "रोमन साम्राज्यको पतन कहिले भयो?",
    options: ["३९५ ई.सं.", "४१० ई.सं.", "४७६ ई.सं.", "५५० ई.सं."],
    answer: "४७६ ई.सं.",
    level: 4,
    category: "world history",
  ),
  Question(
    id: 212,
    question: "महात्मा गान्धीको जन्म कहिले भयो?",
    options: ["१८६९", "१८७०", "१८७१", "१८७२"],
    answer: "१८६९",
    level: 1,
    category: "world history",
  ),
  Question(
    id: 213,
    question: "क्यूबा मिसाइल संकट कहिले भएको थियो?",
    options: ["१९५९", "१९६२", "१९६५", "१९६८"],
    answer: "१९६२",
    level: 5,
    category: "world history",
  ),
  Question(
    id: 214,
    question: "मार्टिन लुथर किङ जूनियर कुन आन्दोलनका नेता थिए?",
    options: [
      "श्रम आन्दोलन",
      "पर्यावरण आन्दोलन",
      "नागरिक अधिकार आन्दोलन",
      "महिला अधिकार आन्दोलन",
    ],
    answer: "नागरिक अधिकार आन्दोलन",
    level: 3,
    category: "world history",
  ),
  Question(
    id: 215,
    question: "पिरामिडहरू कुन प्राचीन सभ्यतासँग सम्बन्धित छन्?",
    options: ["रोमन", "ग्रीक", "इजिप्टियन", "मेसोपोटामिया"],
    answer: "इजिप्टियन",
    level: 1,
    category: "world history",
  ),
  Question(
    id: 216,
    question: "रेनेसाँ (Renaissance) को सुरुवात कुन देशबाट भयो?",
    options: ["फ्रान्स", "इटाली", "जर्मनी", "इङ्गल्याण्ड"],
    answer: "इटाली",
    level: 4,
    category: "world history",
  ),
  Question(
    id: 217,
    question: "भारत कहिले स्वतन्त्र भयो?",
    options: ["१९४५", "१९४७", "१९४८", "१९५०"],
    answer: "१९४७",
    level: 1,
    category: "world history",
  ),
  Question(
    id: 218,
    question: "सोभियत संघको विघटन कहिले भयो?",
    options: ["१९८९", "१९९०", "१९९१", "१९९२"],
    answer: "१९९१",
    level: 3,
    category: "world history",
  ),
  Question(
    id: 219,
    question: "जर्मनीको एकीकरणका लागि कुन व्यक्ति जिम्मेवार थिए?",
    options: [
      "एडोल्फ हिटलर",
      "ओट्टो भोन बिस्मार्क",
      "फ्रेडरिक द ग्रेट",
      "विल्हेल्म I",
    ],
    answer: "ओट्टो भोन बिस्मार्क",
    level: 5,
    category: "world history",
  ),
  Question(
    id: 220,
    question: "चार्ल्स डार्विनले कुन सिद्धान्त प्रतिपादन गरेका थिए?",
    options: [
      "सापेक्षताको सिद्धान्त",
      "विकासवादको सिद्धान्त",
      "गुरुत्वाकर्षणको नियम",
      "क्वान्टम सिद्धान्त",
    ],
    answer: "विकासवादको सिद्धान्त",
    level: 2,
    category: "world history",
  ),

  // --- Nepal Geography ---
  Question(
    id: 301,
    question: "नेपालको सबैभन्दा अग्लो हिमाल कुन हो?",
    options: ["कञ्चनजंघा", "सगरमाथा", "लोत्से", "मकालु"],
    answer: "सगरमाथा",
    level: 1,
    category: "nepal geography",
  ),
  Question(
    id: 302,
    question: "नेपालको सबैभन्दा ठूलो जिल्ला कुन हो?",
    options: ["मुगु", "हुम्ला", "डोल्पा", "जुम्ला"],
    answer: "डोल्पा",
    level: 2,
    category: "nepal geography",
  ),
  Question(
    id: 303,
    question: "नेपालको सबैभन्दा ठूलो राष्ट्रिय निकुञ्ज कुन हो?",
    options: [
      "सगरमाथा राष्ट्रिय निकुञ्ज",
      "चितवन राष्ट्रिय निकुञ्ज",
      "शे-फोक्सुण्डो राष्ट्रिय निकुञ्ज",
      "लाङटाङ राष्ट्रिय निकुञ्ज",
    ],
    answer: "शे-फोक्सुण्डो राष्ट्रिय निकुञ्ज",
    level: 3,
    category: "nepal geography",
  ),
  Question(
    id: 304,
    question: "त्रिवेणी धाम कुन नदीको किनारमा अवस्थित छ?",
    options: ["कोशी", "गण्डकी", "कर्णाली", "बबई"],
    answer: "गण्डकी",
    level: 4,
    category: "nepal geography",
  ),
  Question(
    id: 305,
    question: "नेपालको सबैभन्दा गहिरो ताल कुन हो?",
    options: ["फेवा ताल", "रारा ताल", "शे-फोक्सुण्डो ताल", "गोसाइँकुण्ड"],
    answer: "शे-फोक्सुण्डो ताल",
    level: 5,
    category: "nepal geography",
  ),
  Question(
    id: 306,
    question: "नेपालको कुन जिल्ला 'कफी जोन' को रूपमा चिनिन्छ?",
    options: ["इलाम", "गुल्मी", "सिन्धुपाल्चोक", "काभ्रेपलान्चोक"],
    answer: "गुल्मी",
    level: 6,
    category: "nepal geography",
  ),
  Question(
    id: 307,
    question: "नेपालको कुल क्षेत्रफल कति छ?",
    options: [
      "१,४७,१८१ वर्ग कि.मि.",
      "१,४७,५१६ वर्ग कि.मि.",
      "१,५०,००० वर्ग कि.मि.",
      "१,४०,००० वर्ग कि.मि.",
    ],
    answer: "१,४७,१८१ वर्ग कि.मि.",
    level: 1,
    category: "nepal geography",
  ),
  Question(
    id: 308,
    question: "नेपालको सबैभन्दा लामो नदी कुन हो?",
    options: ["कोशी", "गण्डकी", "कर्णाली", "महाकाली"],
    answer: "कर्णाली",
    level: 2,
    category: "nepal geography",
  ),
  Question(
    id: 309,
    question: "नेपालमा कतिवटा प्रदेश छन्?",
    options: ["५", "६", "७", "८"],
    answer: "७",
    level: 1,
    category: "nepal geography",
  ),
  Question(
    id: 310,
    question: "नेपालको सबैभन्दा होचो ठाउँ कुन हो?",
    options: ["केचनाकलन", "ढेडा", "सुस्ता", "रानीघाट"],
    answer: "केचनाकलन",
    level: 3,
    category: "nepal geography",
  ),
  Question(
    id: 311,
    question: "नेपालको पूर्व-पश्चिम लम्बाइ कति छ?",
    options: ["८०० कि.मि.", "८८५ कि.मि.", "९५० कि.मि.", "७५० कि.मि."],
    answer: "८८५ कि.मि.",
    level: 2,
    category: "nepal geography",
  ),
  Question(
    id: 312,
    question: "नेपालको सबैभन्दा ठूलो वन्यजन्तु आरक्ष कुन हो?",
    options: [
      "कञ्चनजंघा संरक्षण क्षेत्र",
      "अन्नपूर्ण संरक्षण क्षेत्र",
      "ढोरपाटन शिकार आरक्ष",
      "शुक्लाफाँटा राष्ट्रिय निकुञ्ज",
    ],
    answer: "अन्नपूर्ण संरक्षण क्षेत्र",
    level: 4,
    category: "nepal geography",
  ),
  Question(
    id: 313,
    question: "शे-फोक्सुण्डो ताल कुन जिल्लामा अवस्थित छ?",
    options: ["मुगु", "जुम्ला", "डोल्पा", "कालिकोट"],
    answer: "डोल्पा",
    level: 3,
    category: "nepal geography",
  ),
  Question(
    id: 314,
    question: "नेपालका कुन हिमाललाई 'सगरमाथाको प्रवेशद्वार' भनिन्छ?",
    options: ["लाङटाङ", "मकालु", "खुम्बु", "पुमरी"],
    answer: "खुम्बु",
    level: 4,
    category: "nepal geography",
  ),
  Question(
    id: 315,
    question: "नेपालमा 'तामाकोसी' जलविद्युत आयोजना कुन जिल्लामा छ?",
    options: ["सिन्धुपाल्चोक", "दोलखा", "रामेछाप", "काभ्रेपलान्चोक"],
    answer: "दोलखा",
    level: 3,
    category: "nepal geography",
  ),
  Question(
    id: 316,
    question: "नेपालको 'चिया क्षेत्र' को रूपमा कुन जिल्ला प्रसिद्ध छ?",
    options: ["झापा", "इलाम", "पाँचथर", "धनकुटा"],
    answer: "इलाम",
    level: 1,
    category: "nepal geography",
  ),
  Question(
    id: 317,
    question: "नेपालको कुन जिल्ला 'स्याउ' उत्पादनका लागि प्रसिद्ध छ?",
    options: ["मुगु", "जुम्ला", "हुम्ला", "डोल्पा"],
    answer: "जुम्ला",
    level: 2,
    category: "nepal geography",
  ),
  Question(
    id: 318,
    question: "नेपालको 'मनास्लु' हिमाल कुन श्रेणीमा पर्छ?",
    options: [
      "मकालु हिमाल",
      "अन्नपूर्ण हिमाल",
      "मनास्लु हिमाल",
      "कञ्चनजंघा हिमाल",
    ],
    answer: "मनास्लु हिमाल",
    level: 5,
    category: "nepal geography",
  ),
  Question(
    id: 319,
    question: "कोशी नदी नेपालका कति जिल्ला भएर बग्छ?",
    options: ["७", "८", "९", "१०"],
    answer: "७",
    level: 6,
    category: "nepal geography",
  ), // This might need verification depending on the definition of "districts it passes through"
  Question(
    id: 320,
    question: "नेपालको सबैभन्दा ठूलो मानव निर्मित ताल कुन हो?",
    options: ["कमलपोखरी", "इन्द्रसरोवर (कुलेखानी)", "बेगनास ताल", "रुपा ताल"],
    answer: "इन्द्रसरोवर (कुलेखानी)",
    level: 4,
    category: "nepal geography",
  ),

  // --- World Geography ---
  Question(
    id: 401,
    question: "विश्वको सबैभन्दा ठूलो महासागर कुन हो?",
    options: [
      "प्रशान्त महासागर",
      "आन्द्र महासागर",
      "हिन्द महासागर",
      "आर्कटिक महासागर",
    ],
    answer: "प्रशान्त महासागर",
    level: 1,
    category: "world geography",
  ),
  Question(
    id: 402,
    question: "अफ्रिकाको सबैभन्दा अग्लो हिमाल कुन हो?",
    options: [
      "माउन्ट केन्या",
      "माउन्ट किलिमन्जारो",
      "माउन्ट एल्ब्रुस",
      "माउन्ट फुजी",
    ],
    answer: "माउन्ट किलिमन्जारो",
    level: 2,
    category: "world geography",
  ),
  Question(
    id: 403,
    question: "विश्वको सबैभन्दा लामो नदी कुन हो?",
    options: ["नाइल नदी", "अमेजन नदी", "यांग्त्जे नदी", "मिसिसिपी नदी"],
    answer: "नाइल नदी",
    level: 3,
    category: "world geography",
  ),
  Question(
    id: 404,
    question: "विश्वको सबैभन्दा ठूलो मरुभूमि कुन हो?",
    options: [
      "सहारा मरुभूमि",
      "गोबी मरुभूमि",
      "कालाहारी मरुभूमि",
      "अटाकामा मरुभूमि",
    ],
    answer: "सहारा मरुभूमि",
    level: 4,
    category: "world geography",
  ),
  Question(
    id: 405,
    question: "अष्ट्रेलियाको राजधानी कुन हो?",
    options: ["सिड्नी", "मेलबर्न", "क्यान्बेरा", "ब्रिसबेन"],
    answer: "क्यान्बेरा",
    level: 5,
    category: "world geography",
  ),
  Question(
    id: 406,
    question: "उत्तरी अमेरिकाको सबैभन्दा अग्लो शिखर कुन हो?",
    options: [
      "माउन्ट एल्ब्रुस",
      "माउन्ट फुजी",
      "माउन्ट एभरेष्ट",
      "डेनाली (माउन्ट म्याकिन्ले)",
    ],
    answer: "डेनाली (माउन्ट म्याकिन्ले)",
    level: 6,
    category: "world geography",
  ),
  Question(
    id: 407,
    question: "विश्वको सबैभन्दा सानो महाद्वीप कुन हो?",
    options: ["एसिया", "युरोप", "अफ्रिका", "अष्ट्रेलिया"],
    answer: "अष्ट्रेलिया",
    level: 1,
    category: "world geography",
  ),
  Question(
    id: 408,
    question: "इजिप्ट कुन महाद्वीपमा पर्छ?",
    options: ["एसिया", "अफ्रिका", "युरोप", "उत्तरी अमेरिका"],
    answer: "अफ्रिका",
    level: 1,
    category: "world geography",
  ),
  Question(
    id: 409,
    question: "विश्वको सबैभन्दा ठूलो देश (क्षेत्रफलको आधारमा) कुन हो?",
    options: ["चीन", "क्यानडा", "अमेरिका", "रुस"],
    answer: "रुस",
    level: 1,
    category: "world geography",
  ),
  Question(
    id: 410,
    question: "ग्रिनल्याण्ड कुन देशको अधिनमा छ?",
    options: ["क्यानडा", "नर्वे", "डेनमार्क", "आइसल्याण्ड"],
    answer: "डेनमार्क",
    level: 3,
    category: "world geography",
  ),
  Question(
    id: 411,
    question: "एन्डीज पर्वतमाला कुन महाद्वीपमा अवस्थित छ?",
    options: ["एसिया", "युरोप", "उत्तर अमेरिका", "दक्षिण अमेरिका"],
    answer: "दक्षिण अमेरिका",
    level: 2,
    category: "world geography",
  ),
  Question(
    id: 412,
    question: "भिक्टोरिया फल्स कुन नदीमा पर्छ?",
    options: ["नाइल", "कंगो", "जाम्बेजी", "नाइजर"],
    answer: "जाम्बेजी",
    level: 4,
    category: "world geography",
  ),
  Question(
    id: 413,
    question: "मृत सागर (Dead Sea) कुन दुई देशको बीचमा पर्छ?",
    options: [
      "इजिप्ट र सुडान",
      "इजरायल र जोर्डन",
      "लेबनान र सिरिया",
      "टर्की र ग्रीस",
    ],
    answer: "इजरायल र जोर्डन",
    level: 5,
    category: "world geography",
  ),
  Question(
    id: 414,
    question: "विश्वको सबैभन्दा लामो भूमि सीमा कुन दुई देशको बीचमा छ?",
    options: [
      "अमेरिका र मेक्सिको",
      "क्यानडा र अमेरिका",
      "रुस र चीन",
      "भारत र चीन",
    ],
    answer: "क्यानडा र अमेरिका",
    level: 3,
    category: "world geography",
  ),
  Question(
    id: 415,
    question: "इस्तानबुल शहर कुन दुई महाद्वीपमा फैलिएको छ?",
    options: [
      "एसिया र युरोप",
      "युरोप र अफ्रिका",
      "एसिया र अफ्रिका",
      "उत्तर अमेरिका र दक्षिण अमेरिका",
    ],
    answer: "एसिया र युरोप",
    level: 4,
    category: "world geography",
  ),
  Question(
    id: 416,
    question: "विश्वको सबैभन्दा ठूलो ताल (क्षेत्रफलको आधारमा) कुन हो?",
    options: ["सुपिरियर ताल", "भिक्टोरिया ताल", "क्यास्पियन सागर", "आरल सागर"],
    answer: "क्यास्पियन सागर",
    level: 5,
    category: "world geography",
  ),
  Question(
    id: 417,
    question: "भू-मध्यसागर (Mediterranean Sea) कुन महासागरसँग जोडिएको छ?",
    options: [
      "प्रशान्त महासागर",
      "आन्द्र महासागर",
      "हिन्द महासागर",
      "आर्कटिक महासागर",
    ],
    answer: "आन्द्र महासागर",
    level: 2,
    category: "world geography",
  ),
  Question(
    id: 418,
    question: "माउन्ट फुजी कुन देशमा अवस्थित छ?",
    options: ["चीन", "जापान", "कोरिया", "भारत"],
    answer: "जापान",
    level: 1,
    category: "world geography",
  ),
  Question(
    id: 419,
    question: "विश्वको 'कफीको बास्केट' भनिने देश कुन हो?",
    options: ["कोलम्बिया", "भियतनाम", "इथियोपिया", "ब्राजिल"],
    answer: "ब्राजिल",
    level: 6,
    category: "world geography",
  ),
  Question(
    id: 420,
    question: "केप टाउन कुन देशको राजधानी हो?",
    options: ["केन्या", "दक्षिण अफ्रिका", "नाइजेरिया", "मिश्र"],
    answer: "दक्षिण अफ्रिका",
    level: 3,
    category: "world geography",
  ),

  // --- Science ---
  Question(
    id: 501,
    question: "पानीको रासायनिक सूत्र के हो?",
    options: ["CO2", "H2O", "O2", "NaCl"],
    answer: "H2O",
    level: 1,
    category: "science",
  ),
  Question(
    id: 502,
    question: "मानव शरीरमा कति हड्डी हुन्छन्?",
    options: ["२०६", "२१०", "२५०", "३००"],
    answer: "२०६",
    level: 2,
    category: "science",
  ),
  Question(
    id: 503,
    question: "प्रकाश संश्लेषण प्रक्रियामा बिरुवाहरूले कुन ग्यास सोस्छन्?",
    options: ["अक्सिजन", "नाइट्रोजन", "कार्बन डाइअक्साइड", "हाइड्रोजन"],
    answer: "कार्बन डाइअक्साइड",
    level: 3,
    category: "science",
  ),
  Question(
    id: 504,
    question: "विद्युत धारा नाप्न कुन उपकरण प्रयोग गरिन्छ?",
    options: ["भोल्टमिटर", "एमिटर", "ओह्ममिटर", "ब्यारोमिटर"],
    answer: "एमिटर",
    level: 4,
    category: "science",
  ),
  Question(
    id: 505,
    question: "सूर्यको प्रकाश पृथ्वीमा पुग्न कति समय लाग्छ?",
    options: ["८ मिनेट २० सेकेन्ड", "८ मिनेट", "९ मिनेट", "७ मिनेट ५० सेकेन्ड"],
    answer: "८ मिनेट २० सेकेन्ड",
    level: 5,
    category: "science",
  ),
  Question(
    id: 506,
    question: "क्वान्टम सिद्धान्तका प्रतिपादक को हुन्?",
    options: [
      "अल्बर्ट आइन्स्टाइन",
      "म्याक्स प्लांक",
      "इज्याक न्यूटन",
      "निल्स बोर",
    ],
    answer: "म्याक्स प्लांक",
    level: 6,
    category: "science",
  ),
  Question(
    id: 507,
    question: "मानव शरीरको सबैभन्दा ठूलो अंग कुन हो?",
    options: ["मस्तिष्क", "कलेजो", "छाला", "मुटु"],
    answer: "छाला",
    level: 1,
    category: "science",
  ),
  Question(
    id: 508,
    question: "अक्सिजनको प्रतीक के हो?",
    options: ["Ox", "O", "O2", "Oz"],
    answer: "O",
    level: 1,
    category: "science",
  ),
  Question(
    id: 509,
    question: "गुरुत्वाकर्षणको नियम कसले प्रतिपादन गरेका थिए?",
    options: [
      "ग्यालिलियो ग्यालिली",
      "अल्बर्ट आइन्स्टाइन",
      "इज्याक न्यूटन",
      "स्टीफन हकिङ",
    ],
    answer: "इज्याक न्यूटन",
    level: 2,
    category: "science",
  ),
  Question(
    id: 510,
    question: "ध्वनि नाप्ने एकाइ के हो?",
    options: ["भोल्ट", "एम्पियर", "डेसिबल", "वाट"],
    answer: "डेसिबल",
    level: 2,
    category: "science",
  ),
  Question(
    id: 511,
    question: "रक्त समूह पत्ता लगाउने वैज्ञानिक को हुन्?",
    options: [
      "लुई पास्चर",
      "अलेक्जेन्डर फ्लेमिङ",
      "कार्ल ल्यान्डस्टाइनर",
      "रबर्ट कोच",
    ],
    answer: "कार्ल ल्यान्डस्टाइनर",
    level: 3,
    category: "science",
  ),
  Question(
    id: 512,
    question: "मानव शरीरको कुन अंगले रगत फिल्टर गर्छ?",
    options: ["मुटु", "फोक्सो", "कलेजो", "मिर्गौला"],
    answer: "मिर्गौला",
    level: 2,
    category: "science",
  ),
  Question(
    id: 513,
    question: "सूर्यबाट सबैभन्दा नजिकको ग्रह कुन हो?",
    options: ["मंगल", "शुक्र", "बुध", "पृथ्वी"],
    answer: "बुध",
    level: 1,
    category: "science",
  ),
  Question(
    id: 514,
    question: "पेन्सिलिनको आविष्कार कसले गरेका थिए?",
    options: [
      "लुई पास्चर",
      "अलेक्जेन्डर फ्लेमिङ",
      "जोसेफ लिस्टर",
      "एडवर्ड जेनर",
    ],
    answer: "अलेक्जेन्डर फ्लेमिङ",
    level: 3,
    category: "science",
  ),
  Question(
    id: 515,
    question: "समुद्री सतहमा वायुमण्डलीय चाप कति हुन्छ?",
    options: ["७६० एमएम एचजी", "१ एटिएम", "१०१.३२५ किलोपास्कल", "माथिका सबै"],
    answer: "माथिका सबै",
    level: 5,
    category: "science",
  ),
  Question(
    id: 516,
    question: "कुन धातु कोठाको तापक्रममा तरल अवस्थामा हुन्छ?",
    options: ["फलाम", "तामा", "पारो", "चाँदी"],
    answer: "पारो",
    level: 2,
    category: "science",
  ),
  Question(
    id: 517,
    question: "बिरुवाको कुन भागले पानी र खनिज पदार्थ माथि लैजान्छ?",
    options: ["फ्लोएम", "जाइलम", "क्याम्बियम", "कर्टेक्स"],
    answer: "जाइलम",
    level: 4,
    category: "science",
  ),
  Question(
    id: 518,
    question: "सल्फ्युरिक एसिडको रासायनिक सूत्र के हो?",
    options: ["HCl", "HNO3", "H2SO4", "CH3COOH"],
    answer: "H2SO4",
    level: 3,
    category: "science",
  ),
  Question(
    id: 519,
    question: "रेडियोधर्मिता (Radioactivity) को आविष्कार कसले गरेका थिए?",
    options: [
      "मेरी क्युरी",
      "पियरे क्युरी",
      "हेनरी बेक्वेरेल",
      "अर्नेस्ट रदरफोर्ड",
    ],
    answer: "हेनरी बेक्वेरेल",
    level: 6,
    category: "science",
  ),
  Question(
    id: 520,
    question: "मानव शरीरको सबैभन्दा सानो हड्डी कुन हो?",
    options: ["ह्यामर", "एन्भिल", "स्टिरप", "फेमर"],
    answer: "स्टिरप",
    level: 4,
    category: "science",
  ),

  // --- Technology ---
  Question(
    id: 601,
    question: "कम्प्युटरको 'ब्रेन' केलाई भनिन्छ?",
    options: ["RAM", "ROM", "CPU", "Motherboard"],
    answer: "CPU",
    level: 1,
    category: "technology",
  ),
  Question(
    id: 602,
    question: "इन्टरनेटको आविष्कार कसले गरे?",
    options: ["बिल गेट्स", "स्टीव जब्स", "टिम बर्नर्स-ली", "मार्क जुकरबर्ग"],
    answer: "टिम बर्नर्स-ली",
    level: 2,
    category: "technology",
  ),
  Question(
    id: 603,
    question: "पहिलो कम्प्युटर प्रोग्रामर को हुन्?",
    options: [
      "चार्ल्स ब्याबेज",
      "एडा लभलेस",
      "एलन ट्युरिङ",
      "जोन भोन न्यूम्यान",
    ],
    answer: "एडा लभलेस",
    level: 3,
    category: "technology",
  ),
  Question(
    id: 604,
    question: "एन्ड्रोइड अपरेटिङ सिस्टम कुन कम्पनीले विकास गरेको हो?",
    options: ["एप्पल", "माइक्रोसफ्ट", "गुगल", "सामसुङ"],
    answer: "गुगल",
    level: 4,
    category: "technology",
  ),
  Question(
    id: 605,
    question: "ब्लकचेन प्रविधिको आधारभूत तत्व के हो?",
    options: [
      "केन्द्रीकृत सर्भर",
      "वितरित लेजर",
      "एकल डेटाबेस",
      "क्लाउड स्टोरेज",
    ],
    answer: "वितरित लेजर",
    level: 5,
    category: "technology",
  ),
  Question(
    id: 606,
    question:
        "कृत्रिम बुद्धिमत्ता (AI) को क्षेत्रमा 'ट्युरिङ टेस्ट' को मुख्य उद्देश्य के हो?",
    options: [
      "कम्प्युटरको गति मापन गर्न",
      "मानव जस्तै बुद्धिमत्ता अनुकरण गर्न सक्ने क्षमता परीक्षण गर्न",
      "सफ्टवेयर त्रुटिहरू पत्ता लगाउन",
      "डेटा भण्डारण क्षमता जाँच गर्न",
    ],
    answer: "मानव जस्तै बुद्धिमत्ता अनुकरण गर्न सक्ने क्षमता परीक्षण गर्न",
    level: 6,
    category: "technology",
  ),
  Question(
    id: 607,
    question: "वर्ड वाइड वेब (WWW) को आविष्कार कहिले भयो?",
    options: ["१९८९", "१९९०", "१९९१", "१९९२"],
    answer: "१९८९",
    level: 2,
    category: "technology",
  ),
  Question(
    id: 608,
    question: "पहिलो मोबाइल फोन कल कसले गरे?",
    options: [
      "एलेक्जेन्डर ग्राहम बेल",
      "मार्टिन कूपर",
      "थोमस एडिसन",
      "निकोला टेस्ला",
    ],
    answer: "मार्टिन कूपर",
    level: 3,
    category: "technology",
  ),
  Question(
    id: 609,
    question: "कम्प्युटरमा 'फाइल' हरू भण्डारण गर्न कुन यन्त्र प्रयोग गरिन्छ?",
    options: ["रेम", "रोम", "हार्ड डिस्क", "प्रोसेसर"],
    answer: "हार्ड डिस्क",
    level: 1,
    category: "technology",
  ),
  Question(
    id: 610,
    question: "HTTP को पूर्ण रूप के हो?",
    options: [
      "HyperText Transfer Protocol",
      "High Technology Transfer Protocol",
      "Hyper Transfer Text Protocol",
      "Highly Technical Transfer Process",
    ],
    answer: "HyperText Transfer Protocol",
    level: 2,
    category: "technology",
  ),
  Question(
    id: 611,
    question: "पहिलो इ-मेल कसले पठाएका थिए?",
    options: ["बिल गेट्स", "रे टम्लिन्सन", "स्टीव जब्स", "मार्क जुकरबर्ग"],
    answer: "रे टम्लिन्सन",
    level: 4,
    category: "technology",
  ),
  Question(
    id: 612,
    question: "एप्पल कम्पनीको सह-संस्थापक को हुन्?",
    options: ["बिल गेट्स", "मार्क जुकरबर्ग", "स्टीव जब्स", "एलन मस्क"],
    answer: "स्टीव जब्स",
    level: 1,
    category: "technology",
  ),
  Question(
    id: 613,
    question: "५जी (5G) मोबाइल नेटवर्कमा 'जी' को अर्थ के हो?",
    options: ["Gigabyte", "Generation", "Global", "Graphic"],
    answer: "Generation",
    level: 2,
    category: "technology",
  ),
  Question(
    id: 614,
    question: "साइबर सुरक्षामा 'फिसिङ' (Phishing) के हो?",
    options: [
      "कम्प्युटर भाइरसको एक प्रकार",
      "अवैध रूपमा व्यक्तिगत जानकारी प्राप्त गर्ने प्रयास",
      "कम्प्युटर ह्याकिङको एक विधि",
      "डाटा चोरी गर्ने सफ्टवेयर",
    ],
    answer: "अवैध रूपमा व्यक्तिगत जानकारी प्राप्त गर्ने प्रयास",
    level: 4,
    category: "technology",
  ),
  Question(
    id: 615,
    question: "डिजिटल मुद्रा 'बिटकोइन' को आविष्कार कसले गरे?",
    options: ["सतोशी नाकामोटो", "इलन मस्क", "बिल गेट्स", "जेफ बेजोस"],
    answer: "सतोशी नाकामोटो",
    level: 5,
    category: "technology",
  ),
  Question(
    id: 616,
    question:
        "क्लाउड कम्प्यूटिंगमा 'सॉफ्टवेयर एज अ सर्भिस' (SaaS) को उदाहरण कुन हो?",
    options: [
      "माइक्रोसफ्ट अफिस",
      "एडोब फोटोसप",
      "गुगल डक्स",
      "विन्डोज अपरेटिङ सिस्टम",
    ],
    answer: "गुगल डक्स",
    level: 6,
    category: "technology",
  ),
  Question(
    id: 617,
    question: "QR कोडको पूर्ण रूप के हो?",
    options: [
      "Quick Response Code",
      "Quality Recognition Code",
      "Quick Read Code",
      "Quadrant Reference Code",
    ],
    answer: "Quick Response Code",
    level: 3,
    category: "technology",
  ),
  Question(
    id: 618,
    question: "इन्टरनेट प्रोटोकल (IP) एड्रेसका दुई मुख्य संस्करण कुन-कुन हुन्?",
    options: ["IPv3 र IPv4", "IPv4 र IPv6", "IPv5 र IPv7", "IPv10 र IPv12"],
    answer: "IPv4 र IPv6",
    level: 5,
    category: "technology",
  ),
  Question(
    id: 619,
    question:
        "रोबोटिक्समा 'आर्टिफिसियल इन्टेलिजेन्स' (AI) को मुख्य भूमिका के हो?",
    options: [
      "रोबोटको शारीरिक बनावट नियन्त्रण गर्न",
      "रोबोटलाई सिक्न र निर्णय लिन सक्षम बनाउन",
      "रोबोटको आवाज पहिचान गर्न",
      "रोबोटको ब्याट्री व्यवस्थापन गर्न",
    ],
    answer: "रोबोटलाई सिक्न र निर्णय लिन सक्षम बनाउन",
    level: 4,
    category: "technology",
  ),
  Question(
    id: 620,
    question: "पहिलो वेब ब्राउजर के थियो?",
    options: [
      "नेटस्केप नेभिगेटर",
      "मोजाइक",
      "वर्ल्ड वाइड वेब",
      "इन्टरनेट एक्सप्लोरर",
    ],
    answer: "वर्ल्ड वाइड वेब",
    level: 6,
    category: "technology",
  ),

  // --- Sports ---
  Question(
    id: 701,
    question: "फुटबलमा कति खेलाडी हुन्छन्?",
    options: ["९", "१०", "११", "१२"],
    answer: "११",
    level: 1,
    category: "sports",
  ),
  Question(
    id: 702,
    question: "ओलम्पिक खेलहरू कति वर्षमा एक पटक आयोजना हुन्छन्?",
    options: ["२", "३", "४", "५"],
    answer: "४",
    level: 2,
    category: "sports",
  ),
  Question(
    id: 703,
    question: "टेनिसको कुन प्रमुख प्रतियोगितालाई 'ग्रास कोर्ट' मा खेलिन्छ?",
    options: ["फ्रेन्च ओपन", "अस्ट्रेलियन ओपन", "विम्बलडन", "यूएस ओपन"],
    answer: "विम्बलडन",
    level: 3,
    category: "sports",
  ),
  Question(
    id: 704,
    question: "नेपालको राष्ट्रिय खेल कुन हो?",
    options: ["भलिबल", "क्रिकेट", "फुटबल", "कबड्डी"],
    answer: "भलिबल",
    level: 4,
    category: "sports",
  ),
  Question(
    id: 705,
    question: "माइकल जोर्डन कुन खेलका लागि प्रसिद्ध छन्?",
    options: ["फुटबल", "बास्केटबल", "क्रिकेट", "टेनिस"],
    answer: "बास्केटबल",
    level: 5,
    category: "sports",
  ),
  Question(
    id: 706,
    question: "कुन खेलमा 'ग्याम्बिट' शब्द प्रयोग गरिन्छ?",
    options: ["चेस", "ब्याडमिन्टन", "भलिबल", "स्क्वास"],
    answer: "चेस",
    level: 6,
    category: "sports",
  ),
  Question(
    id: 707,
    question: "क्रिकेटमा एउटा ओभरमा कति बल हुन्छन्?",
    options: ["४", "५", "६", "७"],
    answer: "६",
    level: 1,
    category: "sports",
  ),
  Question(
    id: 708,
    question: "फुटबल विश्वकप कति वर्षमा एक पटक आयोजना हुन्छ?",
    options: ["२", "३", "४", "५"],
    answer: "४",
    level: 1,
    category: "sports",
  ),
  Question(
    id: 709,
    question: "विश्वको सबैभन्दा ठूलो खेलकुद कार्यक्रम कुन हो?",
    options: [
      "विश्वकप फुटबल",
      "ओलम्पिक खेलकुद",
      "राष्ट्रमण्डल खेलकुद",
      "एसियाली खेलकुद",
    ],
    answer: "ओलम्पिक खेलकुद",
    level: 2,
    category: "sports",
  ),
  Question(
    id: 710,
    question: "बास्केटबलमा एउटा टोलीमा कति खेलाडी हुन्छन्?",
    options: ["४", "५", "६", "७"],
    answer: "५",
    level: 2,
    category: "sports",
  ),
  Question(
    id: 711,
    question: "टाइगर वुड्स कुन खेलका लागि प्रसिद्ध छन्?",
    options: ["टेनिस", "गोल्फ", "बास्केटबल", "फुटबल"],
    answer: "गोल्फ",
    level: 3,
    category: "sports",
  ),
  Question(
    id: 712,
    question: "कुन देशले सबैभन्दा धेरै ओलम्पिक स्वर्ण पदक जितेको छ?",
    options: ["चीन", "जर्मनी", "अमेरिका", "रुस"],
    answer: "अमेरिका",
    level: 4,
    category: "sports",
  ),
  Question(
    id: 713,
    question: "क्रिकेटमा 'एल बि डब्लु' (LBW) को पूर्ण रूप के हो?",
    options: [
      "Leg Before Wicket",
      "Long Ball Wide",
      "Loose Ball Wicket",
      "Limited Batting Win",
    ],
    answer: "Leg Before Wicket",
    level: 4,
    category: "sports",
  ),
  Question(
    id: 714,
    question: "स्क्वास खेलमा कति खेलाडी खेल्छन्?",
    options: ["१", "२", "३", "४"],
    answer: "२",
    level: 3,
    category: "sports",
  ),
  Question(
    id: 715,
    question: "टेनिसमा 'ग्रान्ड स्ल्याम' अन्तर्गत कति प्रतियोगिता पर्छन्?",
    options: ["२", "३", "४", "५"],
    answer: "४",
    level: 5,
    category: "sports",
  ),
  Question(
    id: 716,
    question: "नेपालको पहिलो ओलम्पियन को हुन्?",
    options: [
      "तेजवीर बुढा",
      "जितबहादुर केसी",
      "वैकुण्ठ मानन्धर",
      "सरस्वती शाह",
    ],
    answer: "जितबहादुर केसी",
    level: 6,
    category: "sports",
  ),
  Question(
    id: 717,
    question: "कुन खेलमा 'नो-बल' र 'वाइड' को नियम हुन्छ?",
    options: ["बास्केटबल", "फुटबल", "क्रिकेट", "भलिबल"],
    answer: "क्रिकेट",
    level: 1,
    category: "sports",
  ),
  Question(
    id: 718,
    question: "हकी खेलमा कति खेलाडी हुन्छन्?",
    options: ["९", "१०", "११", "१२"],
    answer: "११",
    level: 2,
    category: "sports",
  ),
  Question(
    id: 719,
    question: "फुटबलमा 'पेनाल्टी किक' कहाँबाट हान्छ?",
    options: [
      "गोलपोस्टबाट",
      "पेनाल्टी एरियाबाट",
      "मध्य रेखाबाट",
      "कुनै पनि ठाउँबाट",
    ],
    answer: "पेनाल्टी एरियाबाट",
    level: 3,
    category: "sports",
  ),
  Question(
    id: 720,
    question: "बुलाकी आनी' उपनामले चिनिने नेपाली धाविका को हुन्?",
    options: ["मिरा राई", "सरस्वती शाह", "ज्ञानु लामा", "सन्तोषी श्रेष्ठ"],
    answer: "मिरा राai",
    level: 5,
    category: "sports",
  ),

  // --- Culture, Language & Religion ---
  Question(
    id: 801,
    question: "नेपालको राष्ट्रिय भाषा कुन हो?",
    options: ["नेवारी", "मैथिली", "नेपाली", "भोजपुरी"],
    answer: "नेपाली",
    level: 1,
    category: "culture language & religion",
  ),
  Question(
    id: 802,
    question: "बुद्ध धर्मका संस्थापक को हुन्?",
    options: ["महावीर", "गुरु नानक", "सिद्धार्थ गौतम", "शंकराचार्य"],
    answer: "सिद्धार्थ गौतम",
    level: 2,
    category: "culture language & religion",
  ),
  Question(
    id: 803,
    question: "नेपालमा 'गाईजात्रा' पर्व कुन समुदायले मनाउँछन्?",
    options: ["गुरुङ", "नेवार", "शेर्पा", "राई"],
    answer: "नेवार",
    level: 3,
    category: "culture language & religion",
  ),
  Question(
    id: 804,
    question: "विश्वको सबैभन्दा पुरानो धर्म कुन मानिन्छ?",
    options: ["ईसाई धर्म", "इस्लाम धर्म", "हिन्दू धर्म", "बौद्ध धर्म"],
    answer: "हिन्दू धर्म",
    level: 4,
    category: "culture language & religion",
  ),
  Question(
    id: 805,
    question: "'शिरुवा पर्व' कुन समुदायको प्रमुख चाड हो?",
    options: ["थारु", "सन्थाल", "राजवंशी", "किराँत"],
    answer: "सन्थाल",
    level: 5,
    category: "culture language & religion",
  ),
  Question(
    id: 806,
    question: "'महाभारत' कुन भाषामा लेखिएको हो?",
    options: ["पाली", "प्राकृत", "संस्कृत", "अपभ्रंश"],
    answer: "संस्कृत",
    level: 6,
    category: "culture language & religion",
  ),
  Question(
    id: 807,
    question: "नेपालको राष्ट्रिय फूल कुन हो?",
    options: ["गुलाब", "लालीगुराँस", "सयपत्री", "चमेली"],
    answer: "लालीगुराँस",
    level: 1,
    category: "culture language & religion",
  ),
  Question(
    id: 808,
    question: "विश्वमा सबैभन्दा धेरै बोलिने भाषा कुन हो?",
    options: ["अंग्रेजी", "चिनियाँ मन्दारिन", "हिन्दी", "स्पेनिस"],
    answer: "चिनियाँ मन्दारिन",
    level: 2,
    category: "culture language & religion",
  ),
  Question(
    id: 809,
    question: "इस्लाम धर्मको पवित्र ग्रन्थ कुन हो?",
    options: ["वेद", "बाइबल", "कुरान", "त्रिपिटक"],
    answer: "कुरान",
    level: 1,
    category: "culture language & religion",
  ),
  Question(
    id: 810,
    question: "नेपालमा 'घटु' नाच कुन समुदायमा प्रचलित छ?",
    options: ["गुरुङ", "मगर", "थारु", "तामाङ"],
    answer: "थारु",
    level: 3,
    category: "culture language & religion",
  ),
  Question(
    id: 811,
    question: "ईसाई धर्मको प्रमुख चाड कुन हो?",
    options: ["दशैं", "ईद", "क्रिसमस", "दीपावली"],
    answer: "क्रिसमस",
    level: 1,
    category: "culture language & religion",
  ),
  Question(
    id: 812,
    question: "लिम्बू समुदायको मुख्य पर्व कुन हो?",
    options: ["लोसार", "उधौली-चण्डी", "साकेला", "धान नाच"],
    answer: "धान नाच",
    level: 4,
    category: "culture language & religion",
  ),
  Question(
    id: 813,
    question: "'वेद' कति प्रकारका हुन्छन्?",
    options: ["२", "३", "४", "५"],
    answer: "४",
    level: 2,
    category: "culture language & religion",
  ),
  Question(
    id: 814,
    question: "नेपालको 'देउडा' नाच कुन क्षेत्रमा प्रसिद्ध छ?",
    options: ["तराई", "पहाड", "हिमाली", "सुदूरपश्चिम"],
    answer: "सुदूरपश्चिम",
    level: 3,
    category: "culture language & religion",
  ),
  Question(
    id: 815,
    question: "विश्वको सबैभन्दा ठूलो मस्जिद कुन हो?",
    options: [
      "मस्जिद अल-हराम (मक्का)",
      "ब्लु मस्जिद",
      "हसन II मस्जिद",
      "शियान मस्जिद",
    ],
    answer: "मस्जिद अल-हराम (मक्का)",
    level: 5,
    category: "culture language & religion",
  ),
  Question(
    id: 816,
    question: "नेपाली साहित्यमा 'आदिकवि' भनेर कसलाई चिनिन्छ?",
    options: [
      "लक्ष्मीप्रसाद देवकोटा",
      "भानुभक्त आचार्य",
      "मोतीराम भट्ट",
      "बालकृष्ण सम",
    ],
    answer: "भानुभक्त आचार्य",
    level: 1,
    category: "culture language & religion",
  ),
  Question(
    id: 817,
    question: "बौद्ध धर्मको प्रमुख शिक्षा के हो?",
    options: ["कर्मकाण्ड", "आठ गुना मार्ग", "मूर्ति पूजा", "योग"],
    answer: "आठ गुना मार्ग",
    level: 4,
    category: "culture language & religion",
  ),
  Question(
    id: 818,
    question: "नेपालमा 'भोटे जात्रा' कुन जिल्लामा मनाइन्छ?",
    options: ["काठमाडौं", "ललितपुर", "भक्तपुर", "रसुवा"],
    answer: "काठमाडौं",
    level: 5,
    category: "culture language & religion",
  ),
  Question(
    id: 819,
    question: "'गुरू ग्रन्थ साहिब' कुन धर्मको पवित्र ग्रन्थ हो?",
    options: ["हिन्दू धर्म", "जैन धर्म", "सिख धर्म", "बौद्ध धर्म"],
    answer: "सिख धर्म",
    level: 6,
    category: "culture language & religion",
  ),
  Question(
    id: 820,
    question: "नेपालको 'छैठ' पर्व कुन क्षेत्रमा बढी मनाइन्छ?",
    options: ["पहाडी क्षेत्र", "तराई क्षेत्र", "हिमाली क्षेत्र", "उपत्यका"],
    answer: "तराई क्षेत्र",
    level: 2,
    category: "culture language & religion",
  ),

  // --- Education ---
  Question(
    id: 901,
    question: "नेपालको पहिलो विश्वविद्यालय कुन हो?",
    options: [
      "काठमाडौं विश्वविद्यालय",
      "त्रिभुवन विश्वविद्यालय",
      "पोखरा विश्वविद्यालय",
      "लुम्बिनी बौद्ध विश्वविद्यालय",
    ],
    answer: "त्रिभुवन विश्वविद्यालय",
    level: 1,
    category: "education",
  ),
  Question(
    id: 902,
    question: "विश्व साक्षरता दिवस कहिले मनाइन्छ?",
    options: ["सेप्टेम्बर ५", "सेप्टेम्बर ८", "अक्टोबर ५", "अक्टोबर ८"],
    answer: "सेप्टेम्बर ८",
    level: 2,
    category: "education",
  ),
  Question(
    id: 903,
    question: "शिक्षाको अधिकार नेपालको संविधानको कुन भागमा उल्लेख छ?",
    options: [
      "मौलिक हक",
      "राज्यका निर्देशक सिद्धान्त",
      "नागरिक कर्तव्य",
      "माथिका कुनै पनि होइन",
    ],
    answer: "मौलिक हक",
    level: 3,
    category: "education",
  ),
  Question(
    id: 904,
    question: "'गुरुकुल' शिक्षा प्रणाली कुन प्राचीन सभ्यतासँग सम्बन्धित छ?",
    options: ["ग्रीक", "रोमन", "भारतीय", "चिनियाँ"],
    answer: "भारतीय",
    level: 4,
    category: "education",
  ),
  Question(
    id: 905,
    question: "नेपालमा 'खुला विश्वविद्यालय' को स्थापना कहिले भयो?",
    options: ["वि.सं. २०६५", "वि.सं. २०७१", "वि.सं. २०७३", "वि.सं. २०७५"],
    answer: "वि.सं. २०७३",
    level: 5,
    category: "education",
  ),
  Question(
    id: 906,
    question:
        "शिक्षामूलक दृष्टिकोणमा 'ब्लूम्स वर्गीकरण' (Bloom's Taxonomy) को मुख्य उद्देश्य के हो?",
    options: [
      "विद्यार्थीको बौद्धिक क्षमता मापन गर्न",
      "शिक्षणका उद्देश्यहरूलाई विभिन्न स्तरमा वर्गीकरण गर्न",
      "परीक्षाको ढाँचा निर्धारण गर्न",
      "शिक्षकको योग्यता मूल्याङ्कन गर्न",
    ],
    answer: "शिक्षणका उद्देश्यहरूलाई विभिन्न स्तरमा वर्गीकरण गर्न",
    level: 6,
    category: "education",
  ),
  Question(
    id: 907,
    question: "नेपालको पहिलो विद्यालय कुन हो?",
    options: [
      "दरबार हाई स्कूल",
      "आनन्दकुटी विद्यालय",
      "छाउनी पब्लिक स्कूल",
      "त्रिभुवन चन्द्र विद्यालय",
    ],
    answer: "दरबार हाई स्कूल",
    level: 1,
    category: "education",
  ),
  Question(
    id: 908,
    question: "विश्व शिक्षक दिवस कहिले मनाइन्छ?",
    options: ["अक्टोबर ५", "सेप्टेम्बर ५", "नोभेम्बर १४", "जनवरी १"],
    answer: "अक्टोबर ५",
    level: 2,
    category: "education",
  ),
  Question(
    id: 909,
    question: "नेपालमा कति प्रकारका शिक्षा प्रणाली प्रचलित छन्?",
    options: ["२", "३", "४", "५"],
    answer: "३",
    level: 3,
    category: "education",
  ), // Formal, Non-formal, Informal
  Question(
    id: 910,
    question: "'मदरसा' शिक्षा प्रणाली कुन धर्मसँग सम्बन्धित छ?",
    options: ["हिन्दू धर्म", "बौद्ध धर्म", "इस्लाम धर्म", "ईसाई धर्म"],
    answer: "इस्लाम धर्म",
    level: 2,
    category: "education",
  ),
  Question(
    id: 911,
    question: "युनेस्को (UNESCO) को मुख्य उद्देश्य के हो?",
    options: [
      "सैन्य सहयोग",
      "आर्थिक विकास",
      "शिक्षा, विज्ञान र संस्कृति प्रवर्द्धन",
      "स्वास्थ्य सेवा",
    ],
    answer: "शिक्षा, विज्ञान र संस्कृति प्रवर्द्धन",
    level: 4,
    category: "education",
  ),
  Question(
    id: 912,
    question:
        "नेपालमा अनिवार्य तथा निःशुल्क आधारभूत शिक्षाको व्यवस्था कुन तहसम्म छ?",
    options: ["कक्षा ५", "कक्षा ८", "कक्षा १०", "कक्षा १२"],
    answer: "कक्षा ८",
    level: 3,
    category: "education",
  ),
  Question(
    id: 913,
    question: "'ई-लर्निङ' (E-learning) भन्नाले के बुझिन्छ?",
    options: [
      "कक्षाकोठामा गरिने शिक्षा",
      "पुस्तकबाट गरिने अध्ययन",
      "इलेक्ट्रोनिक माध्यमबाट गरिने शिक्षा",
      "सामुदायिक शिक्षा",
    ],
    answer: "इलेक्ट्रोनिक माध्यमबाट गरिने शिक्षा",
    level: 1,
    category: "education",
  ),
  Question(
    id: 914,
    question: "शिक्षकको पेशागत विकासका लागि कुन संस्थाले तालिम दिन्छ?",
    options: [
      "विश्वविद्यालय अनुदान आयोग",
      "राष्ट्रिय परीक्षा बोर्ड",
      "शिक्षक सेवा आयोग",
      "शिक्षक तालिम केन्द्र",
    ],
    answer: "शिक्षक तालिम केन्द्र",
    level: 4,
    category: "education",
  ),
  Question(
    id: 915,
    question: "नेपालमा 'प्राविधिक शिक्षा' कुन संस्थाले प्रदान गर्छ?",
    options: [
      "त्रिभुवन विश्वविद्यालय",
      "काठमाडौं विश्वविद्यालय",
      "सी.टी.ई.भी.टी. (CTEVT)",
      "पोखरा विश्वविद्यालय",
    ],
    answer: "सी.टी.ई.भी.टी. (CTEVT)",
    level: 3,
    category: "education",
  ),
  Question(
    id: 916,
    question: "विद्यालयमा 'गृहकार्य' दिनुको मुख्य उद्देश्य के हो?",
    options: [
      "विद्यार्थीलाई व्यस्त राख्न",
      "शिक्षकको काम घटाउन",
      "सिकेका कुरा अभ्यास गर्न र ज्ञान विस्तार गर्न",
      "अभिभावकलाई संलग्न गराउन",
    ],
    answer: "सिकेका कुरा अभ्यास गर्न र ज्ञान विस्तार गर्न",
    level: 2,
    category: "education",
  ),
  Question(
    id: 917,
    question:
        "'जीवनपर्यन्त शिक्षा' (Lifelong Learning) को अवधारणाले के जनाउँछ?",
    options: [
      "स्कुल र कलेजमा मात्र सिक्नु",
      "जीवनभर सिकिरहनु पर्छ",
      "बूढेसकालमा मात्र सिक्नु",
      "व्यावसायिक तालिम मात्र लिनु",
    ],
    answer: "जीवनभर सिकिरहनु पर्छ",
    level: 5,
    category: "education",
  ),
  Question(
    id: 918,
    question: "शैक्षिक मनोविज्ञानले मुख्यतया केको अध्ययन गर्छ?",
    options: [
      "मानव व्यवहार",
      "पढाइ-लेखाइका प्रक्रियाहरू",
      "शिक्षण विधिहरू",
      "विद्यार्थीको व्यक्तित्व",
    ],
    answer: "पढाइ-लेखाइका प्रक्रियाहरू",
    level: 6,
    category: "education",
  ),
  Question(
    id: 919,
    question: "अन्तर्राष्ट्रिय विद्यार्थी दिवस कहिले मनाइन्छ?",
    options: ["सेप्टेम्बर २०", "नोभेम्बर १७", "डिसेम्बर १०", "जनवरी २६"],
    answer: "नोभेम्बर १७",
    level: 4,
    category: "education",
  ),
  Question(
    id: 920,
    question: "नेपालको 'साक्षरता दर' मापन गर्ने मुख्य आधार के हो?",
    options: [
      "विद्यालय जाने बालबालिकाको संख्या",
      "कक्षा १० उत्तीर्ण गर्नेको संख्या",
      "लेख्न र पढ्न सक्ने जनसंख्या",
      "उच्च शिक्षा हासिल गर्नेको संख्या",
    ],
    answer: "लेख्न र पढ्न सक्ने जनसंख्या",
    level: 5,
    category: "education",
  ),

  // --- Math & IQ ---
  Question(
    id: 1001,
    question: "२ + २ = कति?",
    options: ["३", "४", "५", "६"],
    answer: "४",
    level: 1,
    category: "math & iq",
  ),
  Question(
    id: 1002,
    question: "एउटा त्रिभुजमा कति कोण हुन्छन्?",
    options: ["१", "२", "३", "४"],
    answer: "३",
    level: 2,
    category: "math & iq",
  ),
  Question(
    id: 1003,
    question: "यदि A=1, B=2, C=3 भए, DOG कति हुन्छ?",
    options: ["१८", "२४", "२६", "३०"],
    answer: "२६",
    level: 3,
    category: "math & iq",
  ),
  Question(
    id: 1004,
    question:
        "यदि एक वस्तुको मूल्य रु. ५०० छ र त्यसमा २०% छुट दिइयो भने, छुटपछिको मूल्य कति हुन्छ?",
    options: ["रु. ४००", "रु. ४५०", "रु. ३५०", "रु. ३००"],
    answer: "रु. ४००",
    level: 4,
    category: "math & iq",
  ),
  Question(
    id: 1005,
    question:
        "एउटा घडीमा ३:१५ बजेको छ भने, घण्टाको सुई र मिनेटको सुई बीचको कोण कति हुन्छ?",
    options: ["७.५ डिग्री", "१५ डिग्री", "२२.५ डिग्री", "३० डिग्री"],
    answer: "७.५ डिग्री",
    level: 5,
    category: "math & iq",
  ),
  Question(
    id: 1006,
    question: "कुन संख्या शृंखलामा फरक छ? २, ३, ५, ७, ११, १३, १७, १९, २३, २५",
    options: ["५", "१३", "२३", "२५"],
    answer: "२५",
    level: 6,
    category: "math & iq",
  ),
  Question(
    id: 1007,
    question: "५० को ५०% कति हुन्छ?",
    options: ["१०", "२०", "२५", "३०"],
    answer: "२५",
    level: 1,
    category: "math & iq",
  ),
  Question(
    id: 1008,
    question: "१ दर्जनमा कति वटा हुन्छन्?",
    options: ["१०", "१२", "१५", "२०"],
    answer: "१२",
    level: 1,
    category: "math & iq",
  ),
  Question(
    id: 1009,
    question:
        "यदि १ मिटरमा १०० सेन्टिमिटर हुन्छ भने, २.५ मिटरमा कति सेन्टिमिटर हुन्छ?",
    options: ["१५०", "२००", "२५०", "३००"],
    answer: "२५०",
    level: 2,
    category: "math & iq",
  ),
  Question(
    id: 1010,
    question:
        "एउटा वर्गको चारैतिरको लम्बाइ २० सेन्टिमिटर छ भने, त्यसको क्षेत्रफल कति हुन्छ?",
    options: [
      "२० वर्ग से.मि.",
      "२५ वर्ग से.मि.",
      "१०० वर्ग से.मि.",
      "४०० वर्ग से.मि.",
    ],
    answer: "२५ वर्ग से.मि.",
    level: 3,
    category: "math & iq",
  ), // Assuming perimeter 20cm, side is 5cm, Area 25
  Question(
    id: 1011,
    question: "५, १०, १५, २०, ___? शृंखलाको अर्को संख्या के हो?",
    options: ["२२", "२५", "२८", "३०"],
    answer: "२५",
    level: 1,
    category: "math & iq",
  ),
  Question(
    id: 1012,
    question:
        "एउटा कामलाई ४ जनाले ६ दिनमा पूरा गर्छन् भने, ८ जनाले कति दिनमा पूरा गर्छन्?",
    options: ["२", "३", "४", "५"],
    answer: "३",
    level: 4,
    category: "math & iq",
  ),
  Question(
    id: 1013,
    question: "यदि आज सोमबार हो भने, ७ दिनपछि कुन दिन हुन्छ?",
    options: ["सोमबार", "मंगलबार", "आइतबार", "बुधबार"],
    answer: "सोमबार",
    level: 2,
    category: "math & iq",
  ),
  Question(
    id: 1014,
    question: "४ को वर्गमूल कति हुन्छ?",
    options: ["१", "२", "३", "४"],
    answer: "२",
    level: 1,
    category: "math & iq",
  ),
  Question(
    id: 1015,
    question: "गणितमा 'पाई' (π) को अनुमानित मान कति हुन्छ?",
    options: ["२.१४", "३.१४", "४.१४", "५.१४"],
    answer: "३.१४",
    level: 2,
    category: "math & iq",
  ),
  Question(
    id: 1016,
    question:
        "एउटा वस्तुलाई रु. २०० मा किनेर रु. २५० मा बेच्दा कति प्रतिशत नाफा हुन्छ?",
    options: ["१०%", "१५%", "२०%", "२५%"],
    answer: "२५%",
    level: 3,
    category: "math & iq",
  ),
  Question(
    id: 1017,
    question: "यदि 'APPLE' लाई 'PPLEA' लेखिन्छ भने, 'ORANGE' लाई कसरी लेखिन्छ?",
    options: ["RANGE O", "RANGEOR", "ANGER O", "ANERG O"],
    answer: "RANGE O",
    level: 4,
    category: "math & iq",
  ),
  Question(
    id: 1018,
    question:
        "००:०० देखि २४:०० सम्ममा कति पटक घडीको सुईहरू एकआपसमा ओभरल्याप हुन्छन्?",
    options: ["२१", "२२", "२३", "२४"],
    answer: "२२",
    level: 6,
    category: "math & iq",
  ),
  Question(
    id: 1019,
    question: "वर्गको क्षेत्रफल पत्ता लगाउने सूत्र के हो?",
    options: ["लम्बाइ x चौडाइ", "साइड x साइड", "πr²", "१/२ x आधार x उचाइ"],
    answer: "साइड x साइड",
    level: 1,
    category: "math & iq",
  ),
  Question(
    id: 1020,
    question:
        "तीन जनाको औसत उमेर २० वर्ष छ। यदि उनीहरूमध्ये दुई जनाको उमेर १५ र २५ वर्ष छ भने, तेस्रो व्यक्तिको उमेर कति हुन्छ?",
    options: ["१५", "२०", "२५", "३०"],
    answer: "२०",
    level: 5,
    category: "math & iq",
  ),

  // --- Economic ---
  Question(
    id: 1101,
    question: "नेपाल राष्ट्र बैंकको मुख्य कार्य के हो?",
    options: [
      "व्यापार नियन्त्रण",
      "मुद्रा निष्कासन",
      "कृषि विकास",
      "पर्यटन प्रवर्द्धन",
    ],
    answer: "मुद्रा निष्कासन",
    level: 1,
    category: "economic",
  ),
  Question(
    id: 1102,
    question: "जीडीपी (GDP) को पूर्ण रूप के हो?",
    options: [
      "Gross Domestic Product",
      "General Development Plan",
      "Global Digital Platform",
      "Government Development Project",
    ],
    answer: "Gross Domestic Product",
    level: 2,
    category: "economic",
  ),
  Question(
    id: 1103,
    question: "नेपालको आर्थिक वर्ष कहिलेदेखि कहिलेसम्म हुन्छ?",
    options: [
      "साउन १ देखि असार मसान्त",
      "वैशाख १ देखि चैत मसान्त",
      "पुस १ देखि मंसिर मसान्त",
      "अक्टोबर १ देखि सेप्टेम्बर मसान्त",
    ],
    answer: "साउन १ देखि असार मसान्त",
    level: 3,
    category: "economic",
  ),
  Question(
    id: 1104,
    question: "नेपालमा 'रेमिट्यान्स' को मुख्य स्रोत कुन हो?",
    options: ["पर्यटन", "कृषि", "वैदेशिक रोजगार", "उद्योग"],
    answer: "वैदेशिक रोजगार",
    level: 4,
    category: "economic",
  ),
  Question(
    id: 1105,
    question:
        "कुन सिद्धान्तले 'माग र आपूर्ति' (Demand and Supply) को सम्बन्ध व्याख्या गर्छ?",
    options: [
      "केनेसियन अर्थशास्त्र",
      "मार्क्सवादी अर्थशास्त्र",
      "शास्त्रीय अर्थशास्त्र",
      "नियोक्लासिकल अर्थशास्त्र",
    ],
    answer: "नियोक्लासिकल अर्थशास्त्र",
    level: 5,
    category: "economic",
  ),
  Question(
    id: 1106,
    question: "विश्व व्यापार संगठन (WTO) को मुख्य उद्देश्य के हो?",
    options: [
      "आर्थिक सहायता प्रदान गर्ने",
      "शान्ति स्थापना गर्ने",
      "अन्तर्राष्ट्रिय व्यापारलाई सहज बनाउने",
      "सैन्य गठबन्धन निर्माण गर्ने",
    ],
    answer: "अन्तर्राष्ट्रिय व्यापारलाई सहज बनाउने",
    level: 6,
    category: "economic",
  ),
  Question(
    id: 1107,
    question: "नेपालको केन्द्रीय बैंक कुन हो?",
    options: [
      "कृषि विकास बैंक",
      "नेपाल बैंक लिमिटेड",
      "नेपाल राष्ट्र बैंक",
      "राष्ट्रिय वाणिज्य बैंक",
    ],
    answer: "नेपाल राष्ट्र बैंक",
    level: 1,
    category: "economic",
  ),
  Question(
    id: 1108,
    question: "मुद्रास्फीति (Inflation) भनेको के हो?",
    options: [
      "वस्तु तथा सेवाको मूल्य घट्नु",
      "वस्तु तथा सेवाको मूल्य बढ्नु",
      "मुद्राको मूल्य बढ्नु",
      "बेरोजगारी घट्नु",
    ],
    answer: "वस्तु तथा सेवाको मूल्य बढ्नु",
    level: 2,
    category: "economic",
  ),
  Question(
    id: 1109,
    question: "नेपालको शेयर बजार नियामक निकाय कुन हो?",
    options: [
      "नेपाल राष्ट्र बैंक",
      "अर्थ मन्त्रालय",
      "नेपाल धितोपत्र बोर्ड",
      "धितोपत्र बजार",
    ],
    answer: "नेपाल धितोपत्र बोर्ड",
    level: 3,
    category: "economic",
  ),
  Question(
    id: 1110,
    question: "विकासोन्मुख देशहरूको आर्थिक वृद्धिको मुख्य सूचक के हो?",
    options: [
      "प्रति व्यक्ति आय",
      "जनसंख्या वृद्धि दर",
      "साक्षरता दर",
      "शिशु मृत्यु दर",
    ],
    answer: "प्रति व्यक्ति आय",
    level: 4,
    category: "economic",
  ),
  Question(
    id: 1111,
    question: "बजेट (Budget) कसले पेश गर्छ?",
    options: ["राष्ट्रपति", "प्रधानमन्त्री", "अर्थमन्त्री", "सभामुख"],
    answer: "अर्थमन्त्री",
    level: 1,
    category: "economic",
  ),
  Question(
    id: 1112,
    question: "विश्व बैंकको मुख्य उद्देश्य के हो?",
    options: [
      "शान्ति स्थापना",
      "गरिबी निवारण",
      "पर्यावरण संरक्षण",
      "मानव अधिकार प्रवर्द्धन",
    ],
    answer: "गरिबी निवारण",
    level: 2,
    category: "economic",
  ),
  Question(
    id: 1113,
    question: "नेपालमा 'आन्तरिक राजस्व विभाग' को मुख्य काम के हो?",
    options: [
      "बजेट बनाउनु",
      "कर संकलन गर्नु",
      "आर्थिक नीति बनाउनु",
      "वैदेशिक लगानी आकर्षित गर्नु",
    ],
    answer: "कर संकलन गर्नु",
    level: 3,
    category: "economic",
  ),
  Question(
    id: 1114,
    question: "खुला बजार अर्थतन्त्र (Open Market Economy) को विशेषता के हो?",
    options: [
      "सरकारी नियन्त्रण",
      "निजी क्षेत्रको भूमिका",
      "बन्द व्यापार",
      "आत्मनिर्भरता",
    ],
    answer: "निजी क्षेत्रको भूमिका",
    level: 4,
    category: "economic",
  ),
  Question(
    id: 1115,
    question: "'आयात' (Import) भनेको के हो?",
    options: [
      "वस्तु तथा सेवा निर्यात गर्नु",
      "वस्तु तथा सेवा आयात गर्नु",
      "स्वदेशी उत्पादन बेच्नु",
      "विदेशी मुद्रा कमाउनु",
    ],
    answer: "वस्तु तथा सेवा आयात गर्नु",
    level: 1,
    category: "economic",
  ),
  Question(
    id: 1116,
    question: "नेपालको 'कृषि क्षेत्र' को जीडीपीमा कति योगदान छ?",
    options: ["१०-१५%", "१५-२०%", "२०-२५%", "२५-३०%"],
    answer: "२५-३०%",
    level: 5,
    category: "economic",
  ), // This percentage varies, providing a range.
  Question(
    id: 1117,
    question: "पुँजी बजार (Capital Market) ले मुख्यतया केको कारोबार गर्छ?",
    options: [
      "अल्पावधिक ऋण",
      "दीर्घावधिक ऋण र शेयर",
      "विदेशी मुद्रा",
      "उपभोक्ता वस्तु",
    ],
    answer: "दीर्घावधिक ऋण र शेयर",
    level: 5,
    category: "economic",
  ),
  Question(
    id: 1118,
    question: "'ब्ल्याक मार्केट' (Black Market) भनेको के हो?",
    options: [
      "कानुनी तरिकाले वस्तु बेच्ने ठाउँ",
      "अवैध रूपमा वस्तु तथा सेवाको कारोबार हुने बजार",
      "अनलाइन बजार",
      "सरकारी बजार",
    ],
    answer: "अवैध रूपमा वस्तु तथा सेवाको कारोबार हुने बजार",
    level: 6,
    category: "economic",
  ),
  Question(
    id: 1119,
    question: "सार्क (SAARC) को मुख्य उद्देश्य के हो?",
    options: [
      "सैन्य गठबन्धन",
      "आतंकवाद नियन्त्रण",
      "क्षेत्रीय आर्थिक सहयोग र विकास",
      "सांस्कृतिक आदानप्रदान",
    ],
    answer: "क्षेत्रीय आर्थिक सहयोग र विकास",
    level: 2,
    category: "economic",
  ),
  Question(
    id: 1120,
    question: "नेपालमा 'पाँच वर्षीय योजना' को सुरुवात कहिले भयो?",
    options: ["वि.सं. २०१०", "वि.सं. २०१३", "वि.सं. २०१८", "वि.सं. २०२२"],
    answer: "वि.सं. २०१३",
    level: 3,
    category: "economic",
  ),
];
