class Question {
  final String questionText;
  final List<String> options;
  final int answerIndex; 
  final int id;
  final String category;

  Question({
    required this.questionText,
    required this.options,
    required this.answerIndex, 
    required this.id,
    required this.category,
  });
}

final List<Question> scienceQuestions = [
  // Easy Questions - 2 Options
  Question(id: 1, category: "Science", questionText: " बिरुवाहरूलाई बढ्नको लागि सूर्यको प्रकाश चाहिन्छ। (Do plants need sunlight to grow?)", options: ["हो (Yes)", "होइन (No)"], answerIndex: 0),
  Question(id: 2, category: "Science", questionText: " कोठाको तापक्रममा पानी कुन पदार्थ हो? (What substance is water at room temperature??)", options: ["तरल(Liquid)", "ठोस (Solid)"], answerIndex: 0),
  Question(id: 4, category: "Science", questionText: "के पृथ्वी समतल छ? (Is the Earth flat?)", options: ["हो (Yes)", "होइन (No)"], answerIndex: 1),
  Question(id: 5, category: "Science", questionText: "माछाले फोक्सोबाट हावा फेर्छ ?(Do fish breathe air through lungs?)", options: ["हो (Yes)", "होइन (No)"], answerIndex: 1),

  // Easy Questions - 3 Options
  Question(id: 6, category: "Science", questionText: "मौरीले के बनाउँछ? (What do bees make?)", options: ["दूध (Milk)", "मह (Honey)", "रोटी (Bread)"], answerIndex: 1),
  Question(id: 7, category: "Science", questionText: "यी मध्ये कुन ग्यास हो? (Which of these is a gas?)", options: ["चट्टान (Rock)", "पानी (Water)", "अक्सिजन (Oxygen)"], answerIndex: 2),
  Question(id: 8, category: "Science", questionText: "स्याउलाई रूखबाट तल खसाल्ने के हो? (What makes an apple fall from a tree?)", options: ["हावा (Wind)", "गुरुत्वाकर्षण (Gravity)", "जादू (Magic)"], answerIndex: 1),
  Question(id: 9, category: "Science", questionText: "पृथ्वीको सबैभन्दा नजिकको तारा कुन हो? (Which is the closest star to Earth?)", options: ["चन्द्रमा (Moon)", "सूर्य (Sun)", "मंगल (Mars)"], answerIndex: 1),
  Question(id: 10, category: "Science", questionText: "बिरुवाको कुन भागले सूर्यको प्रकाश सोस्छ? (What part of a plant absorbs sunlight?)", options: ["जरा (Root)", "डाँठ (Stem)", "पात (Leaf)"], answerIndex: 2),
  Question(id: 11, category: "Science", questionText: "H2O को सामान्य नाम के हो? (What is the common name for H2O?)", options: ["नुन (Salt)", "चिनी (Sugar)", "पानी (Water)"], answerIndex: 2),
    Question(id: 13, category: "Science", questionText: "कुन ग्रहलाई 'रातो ग्रह' भनेर चिनिन्छ? (Which planet is known as the 'Red Planet'?)", options: ["शुक्र (Venus)", "मंगल (Mars)", "बृहस्पति (Jupiter)"], answerIndex: 1),
  Question(id: 14, category: "Science", questionText: "झुसिल्कीरा केमा परिणत हुन्छ? (What do caterpillars turn into?)", options: ["माकुरा (Spiders)", "पुतली (Butterflies)", "चरा (Birds)"], answerIndex: 1),
  Question(id: 15, category: "Science", questionText: "बरफलाई केले पगाल्छ? (What makes ice melt?)", options: ["चिसो (Cold)", "ताप (Heat)", "हावा (Wind)"], answerIndex: 1),

  // Gradually increasing difficulty - 4 Options
  Question(id: 16, category: "Science", questionText: "बिरुवाहरूले आफ्नो खाना बनाउने प्रक्रियालाई के भनिन्छ? (What is the process called when plants make their own food?)", options: ["श्वसन (Respiration)", "पाचन (Digestion)", "प्रकाश संश्लेषण (Photosynthesis)", "अंकुरण (Germination)"], answerIndex: 2),
  Question(id: 17, category: "Science", questionText: "मानव श्वासप्रश्वासका लागि कुन तत्व आवश्यक छ? (Which element is essential for human respiration?)", options: ["नाइट्रोजन (Nitrogen)", "कार्बन डाइअक्साइड (Carbon Dioxide)", "हाइड्रोजन (Hydrogen)", "अक्सिजन (Oxygen)"], answerIndex: 3),
  Question(id: 18, category: "Science", questionText: "बलको एकाइ के हो? (What is the unit of force?)", options: ["भोल्ट (Volt)", "एम्पीयर (Ampere)", "न्युटन (Newton)", "वाट (Watt)"], answerIndex: 2),
  Question(id: 19, category: "Science", questionText: "हाम्रो सौर्यमण्डलमा सबैभन्दा ठूलो ग्रह कुन हो? (What is the largest planet in our solar system?)", options: ["पृथ्वी (Earth)", "मंगल (Mars)", "शनि (Saturn)", "बृहस्पति (Jupiter)"], answerIndex: 3),
  Question(id: 20, category: "Science", questionText: "शरीरभर रगत पम्प गर्ने अंग कुन हो? (Which organ pumps blood throughout the body?)", options: ["फोक्सो (Lungs)", "मस्तिष्क (Brain)", "पेट (Stomach)", "मुटु (Heart)"], answerIndex: 3),
  Question(id: 21, category: "Science", questionText: "सुनको रासायनिक प्रतीक के हो? (What is the chemical symbol for gold?)", options: ["Ag", "Fe", "Au (Gold)", "Cu"], answerIndex: 2),
  Question(id: 22, category: "Science", questionText: "भ्याकुममा प्रकाशको गति (लगभग) कति हुन्छ? (What is the speed of light in a vacuum?)", options: ["300 m/s", "3000 km/s", "300,000 km/s", "3,000,000 m/s"], answerIndex: 2),
  Question(id: 23, category: "Science", questionText: "हाम्रो सौर्यमण्डल कुन आकाशगंगाको भाग हो? (Which galaxy is our solar system a part of?)", options: ["एन्ड्रोमेडा (Andromeda)", "ट्रायङ्गुलम (Triangulum)", "पिनव्हील (Pinwheel)", "मिल्की वे (Milky Way)"], answerIndex: 3),
  Question(id: 24, category: "Science", questionText: "रातो रक्त कोशिकाको मुख्य कार्य के हो? (What is the primary function of red blood cells?)", options: ["संक्रमणसँग लड्ने (Fighting infections)", "रगत जम्ने (Clotting blood)", "अक्सिजन बोक्ने (Carrying oxygen)", "खाना पचाउने (Digesting food)"], answerIndex: 2),
  Question(id: 25, category: "Science", questionText: "एक तटस्थ घोलको pH स्तर कति हुन्छ? (What is the pH level of a neutral solution?)", options: ["0", "7", "14", "10"], answerIndex: 1),
  Question(id: 26, category: "Science", questionText: "गतिको साथ सम्बन्धित ऊर्जाको रूप कुन हो? (Which form of energy is associated with motion?)", options: ["स्थितिज ऊर्जा (Potential energy)", "रासायनिक ऊर्जा (Chemical energy)", "गतिज ऊर्जा (Kinetic energy)", "तापीय ऊर्जा (Thermal energy)"], answerIndex: 2),
  Question(id: 27, category: "Science", questionText: "एउटा 'सुटिङ स्टार' वास्तवमा के हो? (What is a 'shooting star' actually?)", options: ["खसेको तारा (A star falling)", "एक धूमकेतु (A comet)", "जलेको उल्कापिण्ड (A meteorite burning up)", "एक क्षुद्रग्रह (An asteroid)"], answerIndex: 2),
  Question(id: 28, category: "Science", questionText: "कुन जनावरले कायापलट गर्छ? (Which animal undergoes metamorphosis?)", options: ["कुकुर (Dog)", "बिरालो (Cat)", "भ्यागुतो (Frog)", "कुखुरा (Chicken)"], answerIndex: 2),
  Question(id: 29, category: "Science", questionText: "कुन सामान्य पदार्थ बिजुलीको राम्रो संवाहक हो? (Which common substance is a good conductor of electricity?)", options: ["काठ (Wood)", "प्लास्टिक (Plastic)", "तामा (Copper)", "रबर (Rubber)"], answerIndex: 2),
  Question(id: 30, category: "Science", questionText: "तापमानको लागि SI एकाइ के हो? (What is the SI unit for temperature?)", options: ["फारेनहाइट (Fahrenheit)", "सेल्सियस (Celsius)", "केल्भिन (Kelvin)", "र्याङ्काइन (Rankine)"], answerIndex: 2),
  Question(id: 31, category: "Science", questionText: "पृथ्वीको ऋतुहरू के कारणले हुन्छन्? (What causes the Earth's seasons?)", options: ["सूर्यबाट दूरी (Distance from Sun)", "चन्द्रमाको परिक्रमा (Moon's orbit)", "पृथ्वीको झुकाव (Earth's tilt)", "सौर ज्वाला (Solar flares)"], answerIndex: 2),
  Question(id: 32, category: "Science", questionText: "कंकालको मुख्य कार्य के हो? (What is the main function of the skeleton?)", options: ["पाचन (Digestion)", "समर्थन र सुरक्षा (Support and protection)", "श्वासप्रश्वास (Breathing)", "रगत पम्प गर्ने (Pumping blood)"], answerIndex: 1),
  Question(id: 33, category: "Science", questionText: "बिरुवाहरूले वायुमण्डलबाट कुन ग्यास सोस्छन्? (Which gas do plants absorb from the atmosphere?)", options: ["अक्सिजन (Oxygen)", "नाइट्रोजन (Nitrogen)", "कार्बन डाइअक्साइड (Carbon Dioxide)", "हाइड्रोजन (Hydrogen)"], answerIndex: 2),
  Question(id: 34, category: "Science", questionText: "गतिलाई प्रतिरोध गर्ने बल के हो? (What is the force that opposes motion?)", options: ["धक्का (Push)", "तान (Pull)", "घर्षण (Friction)", "गुरुत्वाकर्षण (Gravity)"], answerIndex: 2),
  Question(id: 35, category: "Science", questionText: "गुरुत्वाकर्षणले एकसाथ राखेका तारा, ग्यास र धुलोको ठूलो संग्रहलाई के भनिन्छ? (What are large collections of stars, gas, and dust held together by gravity called?)", options: ["ग्रहहरू (Planets)", "धूमकेतुहरू (Comets)", "आकाशगंगाहरू (Galaxies)", "नेबुला (Nebulae)"], answerIndex: 2),
  Question(id: 36, category: "Science", questionText: "जीवनको सबैभन्दा सानो एकाइ के हो? (What is the smallest unit of life?)", options: ["अंग (Organ)", "टिस्यु (Tissue)", "अणु (Molecule)", "कोष (Cell)"], answerIndex: 3),
  Question(id: 37, category: "Science", questionText: "तरल पदार्थ ग्यासमा परिणत हुने प्रक्रियालाई के भनिन्छ? (What is the process of a liquid turning into a gas called?)", options: ["पग्लने (Melting)", "जम्ने (Freezing)", "घनकरण (Condensation)", "वाष्पीकरण (Evaporation)"], answerIndex: 3),
  Question(id: 38, category: "Science", questionText: "तानेको स्प्रिङमा कुन प्रकारको ऊर्जा भण्डारण हुन्छ? (Which type of energy is stored in a stretched spring?)", options: ["गतिज (Kinetic)", "तापीय (Thermal)", "स्थितिज (Potential)", "ध्वनि (Sound)"], answerIndex: 2),
  Question(id: 39, category: "Science", questionText: "चन्द्रमाले सूर्यको प्रकाशलाई रोक्ने घटनालाई के भनिन्छ? (What is the name of the phenomenon where the Moon blocks the Sun's light?)", options: ["चन्द्रग्रहण (Lunar eclipse)", "सौर ज्वाला (Solar flare)", "उल्का वर्षा (Meteor shower)", "सूर्यग्रहण (Solar eclipse)"], answerIndex: 3),
  Question(id: 40, category: "Science", questionText: "मस्तिष्कको कुन भाग सन्तुलन र समन्वयका लागि जिम्मेवार छ? (Which part of the brain is responsible for balance and coordination?)", options: ["सेरेब्रम (Cerebrum)", "ब्रेनस्टेम (Brainstem)", "सेरेबेलम (Cerebellum)", "हाइपोथालेमस (Hypothalamus)"], answerIndex: 2),
  Question(id: 42, category: "Science", questionText: "कुन सिद्धान्तले भन्छ कि आराममा रहेको वस्तु आराममा नै रहन्छ र गतिमा रहेको वस्तु उही गतिमा र उही दिशामा गतिमा रहन्छ जबसम्म असन्तुलित बलद्वारा कार्य गरिँदैन? (What is the principle that states that an object at rest stays at rest and an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force?)", options: ["न्युटनको दोस्रो नियम (Newton's Second Law)", "न्युटनको तेस्रो नियम (Newton's Third Law)", "ऊर्जा संरक्षणको नियम (Law of Conservation of Energy)", "न्युटनको पहिलो नियम (Newton's First Law)"], answerIndex: 3),
  Question(id: 43, category: "Science", questionText: "शनिको वलयहरू मुख्यतया के मिलेर बनेका हुन्छन्? (What are the rings of Saturn primarily made of?)", options: ["ठोस चट्टान (Solid rock)", "पग्लिएको लाभा (Molten lava)", "बरफका कणहरू र चट्टानका टुक्राहरू (Ice particles and rock fragments)", "वायुमण्डलीय ग्यासहरू (Atmospheric gases)"], answerIndex: 2),
  Question(id: 44, category: "Science", questionText: "यी मध्ये कुन पारिस्थितिकी प्रणालीमा अपघटक हो? (Which of these is a decomposer in an ecosystem?)", options: ["रूख (Tree)", "हरिण (Deer)", "च्याउ (Mushroom)", "घाँस (Grass)"], answerIndex: 2),
  Question(id: 45, category: "Science", questionText: "कुन प्रकारको रासायनिक बन्धनमा परमाणुहरू बीच इलेक्ट्रोन जोडीको साझेदारी समावेश हुन्छ? (What type of chemical bond involves the sharing of electron pairs between atoms?)", options: ["आयनिक बन्धन (Ionic bond)", "धातु बन्धन (Metallic bond)", "हाइड्रोजन बन्धन (Hydrogen bond)", "सहसंयोजक बन्धन (Covalent bond)"], answerIndex: 3),
  Question(id: 46, category: "Science", questionText: "बल्ब बाल्दा कुन ऊर्जा रूपान्तरण हुन्छ? (Which energy transformation occurs when a light bulb is turned on?)", options: ["रासायनिकबाट गतिज (Chemical to kinetic)", "यान्त्रिकबाट ध्वनि (Mechanical to sound)", "विद्युतीयबाट प्रकाश र ताप (Electrical to light and heat)", "तापीयबाट स्थितिज (Thermal to potential)"], answerIndex: 2),
  Question(id: 47, category: "Science", questionText: "ब्ल्याक होलबाट केही पनि, प्रकाश समेत, उम्कन नसक्ने सीमाको नाम के हो? (What is the name of the boundary beyond which nothing, not even light, can escape a black hole?)", options: ["सिंगुलारिटी (Singularity)", "एक्रिसन डिस्क (Accretion disk)", "इभेन्ट होराइजन (Event horizon)", "फोटोन स्फेयर (Photon sphere)"], answerIndex: 2),
  Question(id: 48, category: "Science", questionText: "DNA को मुख्य कार्य के हो? (What is the primary function of DNA?)", options: ["कोषको लागि ऊर्जा प्रदान गर्न (To provide energy for the cell)", "रगतमा अक्सिजन ढुवानी गर्न (To transport oxygen in the blood)", "आनुवंशिक जानकारी बोक्न (To carry genetic information)", "मांसपेशीको तन्तु निर्माण गर्न (To build muscle tissue)"], answerIndex: 2),
  Question(id: 49, category: "Science", questionText: "ठोस पदार्थ तरल अवस्थाबाट नजाँदै सीधा ग्यासमा परिणत हुने प्रक्रियालाई के भनिन्छ? (What is the process called where a solid turns directly into a gas without passing through a liquid phase?)", options: ["पग्लने (Melting)", "वाष्पीकरण (Evaporation)", "उर्ध्वपातन (Sublimation)", "घनकरण (Condensation)"], answerIndex: 2),
  Question(id: 50, category: "Science", questionText: "ओमको नियम अनुसार, भोल्टेज (V), करेन्ट (I), र प्रतिरोध (R) बीचको सम्बन्ध के हो? (According to Ohm's Law, what is the relationship between voltage (V), current (I), and resistance (R)?)", options: ["V = I/R", "I = V*R", "R = V*I", "V = I*R"], answerIndex: 3),
   Question(id: 46, category: "Science", questionText: "ध्वनि तरङ्गहरू (Sound waves) के हुन्? (What are sound waves?)", options: ["विद्युत चुम्बकीय तरङ्गहरू (Electromagnetic waves)", "अनुप्रस्थ तरङ्गहरू (Transverse waves)", "अनुदैर्ध्य तरङ्गहरू (Longitudinal waves)", "गुरुत्वाकर्षण तरङ्गहरू (Gravitational waves)"], answerIndex: 2),
  Question(id: 47, category: "Science", questionText: "सूर्यमा कुन ग्यासहरू सबैभन्दा धेरै मात्रामा पाइन्छन्? (Which gases are most abundant in the Sun?)", options: ["अक्सिजन र कार्बन डाइअक्साइड (Oxygen and Carbon Dioxide)", "हीलियम र नाइट्रोजन (Helium and Nitrogen)", "हाइड्रोजन र हीलियम (Hydrogen and Helium)", "नाइट्रोजन र अक्सिजन (Nitrogen and Oxygen)"], answerIndex: 2),
  Question(id: 48, category: "Science", questionText: "मानव शरीरको कुन अंगले रगत फिल्टर (filter) गर्छ र पिसाब बनाउँछ? (Which organ in the human body filters blood and produces urine?)", options: ["कलेजो (Liver)", "मुटु (Heart)", "किड्नी (Kidneys)", "फोक्सो (Lungs)"], answerIndex: 2),
  Question(id: 49, category: "Science", questionText: "कुन रासायनिक तत्वको प्रतीक 'Na' हो? (Which chemical element has the symbol 'Na'?)", options: ["नाइट्रोजन (Nitrogen)", "सोडियम (Sodium)", "निकल (Nickel)", "नियॉन (Neon)"], answerIndex: 1),
  Question(id: 50, category: "Science", questionText: "पृथ्वीको वायुमण्डलको कुन तहमा अधिकांश मौसम (weather) घटनाहरू हुन्छन्? (In which layer of the Earth's atmosphere do most weather phenomena occur?)", options: ["स्ट्र्याटोस्फियर (Stratosphere)", "मेसोस्फियर (Mesosphere)", "ट्रोपोस्फियर (Troposphere)", "थर्मोस्फियर (Thermosphere)"], answerIndex: 2),

  // Medium to Hard Questions - 4 Options
  Question(id: 51, category: "Science", questionText: "कुन वैज्ञानिकले सापेक्षताको सिद्धान्त (Theory of Relativity) प्रतिपादन गरेका थिए? (Which scientist formulated the Theory of Relativity?)", options: ["आइइज्याक न्युटन (Isaac Newton)", "अल्बर्ट आइन्स्टाइन (Albert Einstein)", "ग्यालिलियो ग्यालिलिई (Galileo Galilei)", "स्टीफन हकिङ (Stephen Hawking)"], answerIndex: 1),
  Question(id: 52, category: "Science", questionText: "मानव मस्तिष्कको सबैभन्दा ठूलो भाग कुन हो? (What is the largest part of the human brain?)", options: ["सेरेबेलम (Cerebellum)", "ब्रेनस्टेम (Brainstem)", "सेरेब्रम (Cerebrum)", "मेडुला ओब्लोन्गाटा (Medulla Oblongata)"], answerIndex: 2),
  Question(id: 53, category: "Science", questionText: "पिरियोडिक टेबल (Periodic Table) मा कुल कति ज्ञात तत्वहरू छन्? (How many known elements are there in the Periodic Table?)", options: ["९२ (92)", "१०० (100)", "११८ (118)", "१२० (120)"], answerIndex: 2),
  Question(id: 54, category: "Science", questionText: "ध्वनिको तीव्रता (intensity) मापन गर्न कुन एकाइ प्रयोग गरिन्छ? (Which unit is used to measure the intensity of sound?)", options: ["हर्ज (Hertz)", "भोल्ट (Volt)", "डेसिबल (Decibel)", "एम्पीयर (Ampere)"], answerIndex: 2),
  Question(id: 55, category: "Science", questionText: "ब्ल्याक होल (Black hole) ले प्रकाशलाई समेत किन उम्कन दिँदैन? (Why does a black hole not allow even light to escape?)", options: ["यसको चुम्बकीय क्षेत्रको कारणले (Due to its magnetic field)", "यसको उच्च तापमानको कारणले (Due to its high temperature)", "यसको अत्यधिक गुरुत्वाकर्षण बलको कारणले (Due to its immense gravitational force)", "यसको कम घनत्वको कारणले (Due to its low density)"], answerIndex: 2),
  Question(id: 56, category: "Science", questionText: "डार्विनले (Darwin) कुन सिद्धान्त प्रतिपादन गरेका थिए? (Which theory did Darwin propose?)", options: ["सापेक्षताको सिद्धान्त (Theory of Relativity)", "गुरुत्वाकर्षणको नियम (Law of Gravity)", "प्राकृतिक छनोटको सिद्धान्त (Theory of Natural Selection)", "बिग ब्यांग सिद्धान्त (Big Bang Theory)"], answerIndex: 2),
  Question(id: 57, category: "Science", questionText: "कुन रासायनिक प्रतिक्रियामा ताप उत्पन्न हुन्छ? (Which chemical reaction generates heat?)", options: ["एन्डोथर्मिक (Endothermic)", "एक्जोथर्मिक (Exothermic)", "रिडक्स (Redox)", "न्यूट्रलाइजेशन (Neutralization)"], answerIndex: 1),
  Question(id: 58, category: "Science", questionText: "विद्युत प्रतिरोधको (electrical resistance) एकाइ के हो? (What is the unit of electrical resistance?)", options: ["भोल्ट (Volt)", "एम्पीयर (Ampere)", "ओम (Ohm)", "वाट (Watt)"], answerIndex: 2),
  Question(id: 59, category: "Science", questionText: "पृथ्वीको वायुमण्डलको कुन तहले पराबैंगनी (ultraviolet) विकिरणबाट हामीलाई बचाउँछ? (Which layer of Earth's atmosphere protects us from ultraviolet radiation?)", options: ["ट्रोपोस्फियर (Troposphere)", "स्ट्र्याटोस्फियर (Stratosphere)", "मेसोस्फियर (Mesosphere)", "थर्मोस्फियर (Thermosphere)"], answerIndex: 1),
  Question(id: 60, category: "Science", questionText: "मानव शरीरमा सबैभन्दा सानो हड्डी कुन हो? (What is the smallest bone in the human body?)", options: ["फिमर (Femur)", "स्टेपीज (Stapes)", "रेडियस (Radius)", "टिबिया (Tibia)"], answerIndex: 1),
  Question(id: 61, category: "Science", questionText: "कुन ग्यासले 'ग्रीनहाउस प्रभाव' (Greenhouse Effect) मा सबैभन्दा बढी योगदान पुर्‍याउँछ? (Which gas contributes most to the 'Greenhouse Effect'?)", options: ["अक्सिजन (Oxygen)", "नाइट्रोजन (Nitrogen)", "कार्बन डाइअक्साइड (Carbon Dioxide)", "मिथेन (Methane)"], answerIndex: 2),
  Question(id: 62, category: "Science", questionText: "सूर्यको प्रकाशको सात रङ्गहरूलाई छुट्याउने प्रक्रियालाई के भनिन्छ? (What is the process of splitting white light into its seven constituent colors called?)", options: ["परावर्तन (Reflection)", "अपवर्तन (Refraction)", "विकिरण (Dispersion)", "ध्रुवीकरण (Polarization)"], answerIndex: 2),
  Question(id: 63, category: "Science", questionText: "मानव शरीरमा रगत जम्न (blood clotting) कुन भिटामिन आवश्यक छ? (Which vitamin is essential for blood clotting in the human body?)", options: ["भिटामिन ए (Vitamin A)", "भिटामिन बी (Vitamin B)", "भिटामिन सी (Vitamin C)", "भिटामिन के (Vitamin K)"], answerIndex: 3),
  Question(id: 64, category: "Science", questionText: "पृथ्वीको सबैभन्दा ठूलो मरुभूमि (desert) कुन हो? (What is the largest desert in the world?)", options: ["सहारा मरुभूमि (Sahara Desert)", "गोबी मरुभूमि (Gobi Desert)", "अन्टार्कटिक ध्रुवीय मरुभूमि (Antarctic Polar Desert)", "अरेबियन मरुभूमि (Arabian Desert)"], answerIndex: 2),
  Question(id: 65, category: "Science", questionText: "पानीको सतहमा पानी किन तैरन्छ? (Why does ice float on water?)", options: ["यो चिसो भएकोले (Because it's cold)", "यो हल्का भएकोले (Because it's light)", "यसको घनत्व पानी भन्दा कम भएकोले (Because its density is less than water)", "पानीले यसलाई धक्का दिने भएकोले (Because water pushes it up)"], answerIndex: 2),
  Question(id: 66, category: "Science", questionText: "बोटबिरुवामा पानी र खनिज (minerals) कसरी माथि चढ्छ? (How do water and minerals ascend in plants?)", options: ["फोटोट्रोपिज्म (Phototropism)", "हाइड्रोट्रोपिज्म (Hydrotropism)", "जाइलम (Xylem) मार्फत (Through Xylem)", "फ्लोएम (Phloem) मार्फत (Through Phloem)"], answerIndex: 2),
  Question(id: 67, category: "Science", questionText: "न्युक्लियर फ्युजन (Nuclear fusion) कहाँ हुन्छ? (Where does nuclear fusion occur?)", options: ["पृथ्वीको कोर (Earth's core)", "सूर्य (Sun)", "ज्वालामुखी (Volcanoes)", "चन्द्रमा (Moon)"], answerIndex: 1),
  Question(id: 68, category: "Science", questionText: "मानव शरीरमा रगतको रातो रङ्ग कुन पिग्मेन्ट (pigment) को कारणले हुन्छ? (Which pigment is responsible for the red color of blood in the human body?)", options: ["क्लोरोफिल (Chlorophyll)", "मेलानिन (Melanin)", "हेमोग्लोबिन (Hemoglobin)", "क्यारोटिन (Carotene)"], answerIndex: 2),
  Question(id: 69, category: "Science", questionText: "ध्वनि तरङ्गहरू खाली ठाउँमा (vacuum) किन यात्रा गर्न सक्दैनन्? (Why can't sound waves travel in a vacuum?)", options: ["तिनीहरूलाई ऊर्जा चाहिन्छ (They need energy)", "तिनीहरूलाई माध्यम चाहिन्छ (They need a medium)", "तिनीहरू धेरै बिस्तारै यात्रा गर्छन् (They travel too slowly)", "तिनीहरू धेरै छिटो यात्रा गर्छन् (They travel too fast)"], answerIndex: 1),
  Question(id: 70, category: "Science", questionText: "दूरबीन (telescope) को आविष्कार कसले गरेका थिए? (Who invented the telescope?)", options: ["आइज्याक न्युटन (Isaac Newton)", "ग्यालिलियो ग्यालिलिई (Galileo Galilei)", "जोहानेस केप्लर (Johannes Kepler)", "निकोलस कोपरनिकस (Nicolaus Copernicus)"], answerIndex: 1),
  Question(id: 71, category: "Science", questionText: "कुन धातु (metal) कोठाको तापक्रममा तरल अवस्थामा हुन्छ? (Which metal is liquid at room temperature?)", options: ["फलाम (Iron)", "तामा (Copper)", "पारो (Mercury)", "चाँदी (Silver)"], answerIndex: 2),
  Question(id: 72, category: "Science", questionText: "प्रकाशको सबैभन्दा छिटो गति कुन माध्यममा हुन्छ? (In which medium does light travel fastest?)", options: ["पानी (Water)", "हावा (Air)", "शून्य (Vacuum)", "हिरा (Diamond)"], answerIndex: 2),
  Question(id: 73, category: "Science", questionText: "मानव शरीरको कुन ग्रंथिले (gland) वृद्धि हर्मोन (growth hormone) उत्पादन गर्छ? (Which gland in the human body produces growth hormone?)", options: ["थाइरोइड (Thyroid)", "पिट्युटरी (Pituitary)", "एड्रिनल (Adrenal)", "प्यान्क्रियाज (Pancreas)"], answerIndex: 1),
  Question(id: 74, category: "Science", questionText: "केपलरका (Kepler) नियमहरू केसँग सम्बन्धित छन्? (Kepler's laws are related to what?)", options: ["ग्रहहरूको गति (Planetary motion)", "बल र गति (Force and motion)", "ऊर्जा संरक्षण (Conservation of energy)", "तापगति विज्ञान (Thermodynamics)"], answerIndex: 0),
  Question(id: 75, category: "Science", questionText: "सूर्यग्रहण (Solar eclipse) कहिले हुन्छ? (When does a solar eclipse occur?)", options: ["पृथ्वी, सूर्य र चन्द्रमाको बीचमा आउँदा (When Earth comes between Sun and Moon)", "सूर्य, पृथ्वी र चन्द्रमाको बीचमा आउँदा (When Sun comes between Earth and Moon)", "चन्द्रमा, पृथ्वी र सूर्यको बीचमा आउँदा (When Moon comes between Earth and Sun)", "सूर्य र चन्द्रमा एउटै रेखामा नहुँदा (When Sun and Moon are not in alignment)"], answerIndex: 2),

  // Hard Questions - 4 Options
  Question(id: 76, category: "Science", questionText: "जेनेटिक कोड (Genetic code) कसले पत्ता लगाएका थिए? (Who discovered the genetic code?)", options: ["जेम्स वाटसन (James Watson)", "फ्रान्सिस क्रिक (Francis Crick)", "मार्शल निरेनबर्ग (Marshall Nirenberg)", "रोजालिन्ड फ्र्याङ्कलिन (Rosalind Franklin)"], answerIndex: 2),
  Question(id: 77, category: "Science", questionText: "कुन कणमा कुनै विद्युत आवेश (electric charge) हुँदैन? (Which particle has no electric charge?)", options: ["प्रोटोन (Proton)", "इलेक्ट्रोन (Electron)", "न्युट्रोन (Neutron)", "पोजिट्रोन (Positron)"], answerIndex: 2),
  Question(id: 78, category: "Science", questionText: "कुन रासायनिक तत्वलाई 'जीवनको तत्व' (element of life) भनिन्छ? (Which chemical element is called the 'element of life'?)", options: ["अक्सिजन (Oxygen)", "नाइट्रोजन (Nitrogen)", "कार्बन (Carbon)", "हाइड्रोजन (Hydrogen)"], answerIndex: 2),
  Question(id: 79, category: "Science", questionText: "पृथ्वीको चुम्बकीय क्षेत्र (magnetic field) के कारणले उत्पन्न हुन्छ? (What causes Earth's magnetic field?)", options: ["चन्द्रमाको गुरुत्वाकर्षण (Moon's gravity)", "बाहिरी कोरमा तरल फलामको संवहन (Convection of liquid iron in the outer core)", "सूर्यको विकिरण (Solar radiation)", "महासागरको प्रवाह (Ocean currents)"], answerIndex: 1),
  Question(id: 80, category: "Science", questionText: "पवन ऊर्जा (Wind energy) को रूपान्तरण कसरी हुन्छ? (How is wind energy converted?)", options: ["सोलार प्यानलबाट (Through solar panels)", "टर्बाइनबाट (Through turbines)", "जियोथर्मल प्लान्टबाट (Through geothermal plants)", "बायोमास प्लान्टबाट (Through biomass plants)"], answerIndex: 1),

  // Hard Questions - 5 Options
  Question(id: 81, category: "Science", questionText: "क्वान्टम मेकानिक्स (Quantum mechanics) को आधारभूत सिद्धान्त के हो? (What is a fundamental principle of Quantum Mechanics?)", options: ["गुरुत्वाकर्षणको नियम (Law of Gravitation)", "ऊर्जा संरक्षणको नियम (Law of Conservation of Energy)", "अनिश्चितता सिद्धान्त (Uncertainty Principle)", "सापेक्षताको सिद्धान्त (Theory of Relativity)", "तापगति विज्ञानको नियम (Laws of Thermodynamics)"], answerIndex: 2),
  Question(id: 82, category: "Science", questionText: "मानव शरीरमा सबैभन्दा बलियो मांसपेशी कुन हो? (Which is the strongest muscle in the human body?)", options: ["फिमर (Femur)", "जिभ्रो (Tongue)", "मासेटर (Masseter)", "ग्लुटियस म्याक्सिमस (Gluteus maximus)", "कार्डियाक मांसपेशी (Cardiac muscle)"], answerIndex: 2),
  Question(id: 83, category: "Science", questionText: "रसायन विज्ञानमा, अम्ल र क्षार (acid and base) बीचको प्रतिक्रियालाई के भनिन्छ? (In chemistry, what is the reaction between an acid and a base called?)", options: ["अक्सिडेशन (Oxidation)", "रिडक्सन (Reduction)", "न्यूट्रलाइजेशन (Neutralization)", "संक्षेपण (Condensation)", "पोलिमराइजेशन (Polymerization)"], answerIndex: 2),
  Question(id: 84, category: "Science", questionText: "सुपरनोभा (Supernova) के हो? (What is a Supernova?)", options: ["नयाँ ताराको जन्म (Birth of a new star)", "एक ताराको विस्फोट (Explosion of a star)", "एक आकाशगंगाको टक्कर (Collision of galaxies)", "एक ब्ल्याक होलको गठन (Formation of a black hole)", "एक ग्रहको मृत्यु (Death of a planet)"], answerIndex: 1),
  Question(id: 85, category: "Science", questionText: "मानव शरीरमा 'पावरहाउस' (powerhouse) भनेर कुन अंगलाई चिनिन्छ? (Which organelle is known as the 'powerhouse' of the human cell?)", options: ["न्युक्लियस (Nucleus)", "राइबोसोम (Ribosome)", "माइटोकोन्ड्रिया (Mitochondria)", "गल्जी उपकरण (Golgi apparatus)", "इन्डोप्लाज्मिक रेटिकुलम (Endoplasmic Reticulum)"], answerIndex: 2),
  Question(id: 86, category: "Science", questionText: "कुन ग्यासलाई ओजोन तह (Ozone layer) लाई क्षति पुर्‍याउने मुख्य कारक मानिन्छ? (Which gas is considered the primary cause of damage to the Ozone layer?)", options: ["कार्बन डाइअक्साइड (Carbon Dioxide)", "मिथेन (Methane)", "नाइट्रस अक्साइड (Nitrous Oxide)", "क्लोरोफ्लोरोकार्बन (CFCs)", "सल्फर डाइअक्साइड (Sulfur Dioxide)"], answerIndex: 3),
  Question(id: 87, category: "Science", questionText: "प्रकाशको कुन गुणले इन्धन तरङ्गहरू (light waves) लाई एकअर्कासँग विचलित हुन दिन्छ? (Which property of light waves allows them to interfere with each other?)", options: ["परावर्तन (Reflection)", "अपवर्तन (Refraction)", "विसरण (Diffraction)", "व्यतिकरण (Interference)", "ध्रुवीकरण (Polarization)"], answerIndex: 3),
  Question(id: 88, category: "Science", questionText: "मानव शरीरमा कुन हर्मोनले रक्तचाप (blood pressure) र मुटुको धडकन (heart rate) नियन्त्रण गर्छ? (Which hormone in the human body controls blood pressure and heart rate?)", options: ["इन्सुलिन (Insulin)", "थाइरोक्सिन (Thyroxine)", "एड्रिनालिन (Adrenaline)", "इस्ट्रोजेन (Estrogen)", "टेस्टोस्टेरोन (Testosterone)"], answerIndex: 2),
  Question(id: 89, category: "Science", questionText: "कुन सिद्धान्तले बताउँछ कि पृथ्वीको सतह ठूला प्लेटहरू (plates) ले बनेको छ जुन निरन्तर चलिरहन्छन्? (Which theory explains that Earth's surface is composed of large plates that are constantly moving?)", options: ["गुरुत्वाकर्षण सिद्धान्त (Gravitational Theory)", "Continental Drift Theory", "प्लेट टेक्टोनिक्स सिद्धान्त (Plate Tectonics Theory)", "ज्वालामुखी सिद्धान्त (Volcanic Theory)", "भूगर्भीय अपरदन सिद्धान्त (Geological Erosion Theory)"], answerIndex: 2),
  Question(id: 90, category: "Science", questionText: "सूर्यबाट पृथ्वीसम्म प्रकाश पुग्न लगभग कति समय लाग्छ? (Approximately how long does it take for light from the Sun to reach Earth?)", options: ["१ मिनेट (1 minute)", "४ मिनेट (4 minutes)", "८ मिनेट (8 minutes)", "१२ मिनेट (12 minutes)", "२० मिनेट (20 minutes)"], answerIndex: 2),
  Question(id: 91, category: "Science", questionText: "बायोलोजीमा, क्रसिङ ओभर (crossing over) प्रक्रिया कहाँ हुन्छ? (In biology, where does the process of crossing over occur?)", options: ["माइटोसिसमा (In Mitosis)", "मियोसिसको प्रोफेज I मा (In Prophase I of Meiosis)", "फर्टिलाइजेशनमा (In Fertilization)", "माइटोसिसको मेटाफेजमा (In Metaphase of Mitosis)", "फ्युजनमा (In Fusion)"], answerIndex: 1),
  Question(id: 92, category: "Science", questionText: "कुन प्रकारको विकिरण (radiation) मा सबैभन्दा कम ऊर्जा हुन्छ? (Which type of electromagnetic radiation has the lowest energy?)", options: ["गामा किरण (Gamma rays)", "एक्स-रे (X-rays)", "पराबैंगनी किरण (Ultraviolet rays)", "रेडियो तरङ्गहरू (Radio waves)", "इन्फ्रारेड (Infrared)"], answerIndex: 3),
  Question(id: 93, category: "Science", questionText: "आधुनिक आवधिक तालिका (Modern Periodic Table) कसले विकास गरेका थिए? (Who developed the Modern Periodic Table?)", options: ["जोन डाल्टन (John Dalton)", "दिमित्री मेन्डेलिभ (Dmitri Mendeleev)", "अर्नेस्ट रदरफोर्ड (Ernest Rutherford)", "निल्स बोर (Niels Bohr)", "हेनरी मोस्ले (Henry Moseley)"], answerIndex: 4),
  Question(id: 94, category: "Science", questionText: "ठूलो मात्रामा ऊर्जा उत्पादनका लागि सूर्यले कुन प्रक्रिया प्रयोग गर्छ? (Which process does the Sun use to produce vast amounts of energy?)", options: ["रासायनिक प्रतिक्रिया (Chemical reactions)", "न्युक्लियर फ्युजन (Nuclear fusion)", "न्युक्लियर फिजन (Nuclear fission)", "गुरुत्वाकर्षण संकुचन (Gravitational contraction)", "थर्मल विस्तार (Thermal expansion)"], answerIndex: 1),
  Question(id: 95, category: "Science", questionText: "मानव शरीरमा कोशिकाको आनुवंशिक सामग्री (genetic material) कहाँ भण्डार हुन्छ? (Where is the genetic material of a cell stored in the human body?)", options: ["साइटोप्लाज्म (Cytoplasm)", "राइबोसोम (Ribosome)", "माइटोकोन्ड्रिया (Mitochondria)", "न्युक्लियस (Nucleus)", "सेल मेम्ब्रेन (Cell membrane)"], answerIndex: 3),
  Question(id: 96, category: "Science", questionText: "समुद्रको गहिराइ मापन गर्न कुन उपकरण प्रयोग गरिन्छ? (Which instrument is used to measure the depth of the ocean?)", options: ["ब्यारोमिटर (Barometer)", "एनिमोटर (Anemometer)", "फ्यादोमिटर (Fathometer)", "हाइड्रोमिटर (Hydrometer)", "सेलिमोमिटर (Salinometer)"], answerIndex: 2),
  Question(id: 97, category: "Science", questionText: "कुन ग्रहलाई 'हिराको वर्षा' (diamond rain) हुने भनेर चिनिन्छ? (Which planet is known to have 'diamond rain'?)", options: ["मंगल (Mars)", "बृहस्पति (Jupiter)", "शनि (Saturn)", "नेप्च्युन (Neptune)", "युरेनस (Uranus)"], answerIndex: 3),
  Question(id: 98, category: "Science", questionText: "एक तत्वको समस्थानिक (isotopes) मा के फरक हुन्छ? (What is the difference in isotopes of an element?)", options: ["प्रोटोनको संख्या (Number of protons)", "इलेक्ट्रोनको संख्या (Number of electrons)", "न्युट्रोनको संख्या (Number of neutrons)", "परमाणु संख्या (Atomic number)", "रासायनिक गुणहरू (Chemical properties)"], answerIndex: 2),
  Question(id: 99, category: "Science", questionText: "प्रकाशको परावर्तनको (reflection of light) नियम के हो? (What is the law of reflection of light?)", options: ["आपतन कोण परावर्तन कोण भन्दा ठूलो हुन्छ (Angle of incidence is greater than angle of reflection)", "आपतन कोण परावर्तन कोण भन्दा सानो हुन्छ (Angle of incidence is smaller than angle of reflection)", "आपतन कोण परावर्तन कोण बराबर हुन्छ (Angle of incidence is equal to angle of reflection)", "प्रकाश सिधा रेखामा यात्रा गर्छ (Light travels in a straight line)", "प्रकाशको गति परिवर्तन हुन्छ (Speed of light changes)"], answerIndex: 2),
  Question(id: 100, category: "Science", questionText: "जीवविज्ञानमा, 'सर्वाइभल अफ द फिटेस्ट' (survival of the fittest) को अवधारणा कसले प्रतिपादन गरेका थिए? (In biology, who coined the concept of 'survival of the fittest'?)", options: ["चार्ल्स डार्विन (Charles Darwin)", "ग्रेगर मेन्डेल (Gregor Mendel)", "लुइस पाश्चर (Louis Pasteur)", "हर्बर्ट स्पेन्सर (Herbert Spencer)", "कार्ल लिनियस (Carl Linnaeus)"], answerIndex: 3),

];

